In [41]:
import os
import json

import google.generativeai as genai
from openai import OpenAI
from common_utils.api_key_constants import API_KEY_CONSTANTS_OBJ as API_Key_Constants
import anthropic
import pandas as pd

In [2]:
if not os.environ.get("ANTHROPIC_API_KEY"):
    os.environ["ANTHROPIC_API_KEY"] = API_Key_Constants.ANTHROPIC_API_KEY
genai.configure(api_key=API_Key_Constants.GEMINI_API_KEY)
DEEPSEEK_LOCAL_API_CLIENT = OpenAI(base_url="http://127.0.0.1:1234/v1", api_key="lm-studio")
DEEPSEEK_API_CLIENT = OpenAI(base_url="https://api.deepseek.com", api_key=API_Key_Constants.DEEPSEEK_API_KEY)
OPENAI_CLIENT = OpenAI(api_key=API_Key_Constants.OPENAI_API_KEY) 
ANTHROPIC_CLIENT = anthropic.Anthropic()
XAI_CLIENT = OpenAI(
  api_key=API_Key_Constants.XAI_API_KEY,
  base_url="https://api.x.ai/v1",
)
MODEL = "deepseek-r1-distill-qwen-7b"

In [5]:
def salvage_json_from_llm_response(response,error):
    """
    Uses GPT to salvage JSON response out of a given response, trying to solve the JSONDecodeError
    """
    system_prompt = """
    You are an expert at correcting invalid jsons. 
    You will be given a set of text, which was supposed to be in the format of a json, but isnt due to an error in the text (which will be provided). 
    Your Task is to try to create a proper JSON response out of the given text.
    Use your understanding to assign improper values of the json to either a new key, or to arrange it properly inside an existing key.
    Your response must strictly only be a JSON.
    """ 
    user_input = f"""
    invalid json text: {response},
    
    json decoding error: {error}
    """
    response = OPENAI_CLIENT.chat.completions.create(
                    model='gpt-4o',
                    temperature=0.8,
                    messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input},
            ]
                )
    
    resp = response.choices[0].message.content
    resp = resp.replace("json","").replace("`","").replace("\n",'')
    print("Salvaging LLM Response")
    print(resp)
    return json.loads(resp)

def process_deepseek_output(response):
    """
    Force Output a json if present in deepseek response
    """
    response_text = response
    response_json = None
    stop = False
    while True:
        valid_text,processed_output = process_deepseek_output_helper(response_text)
        if valid_text:
            response_json = processed_output
            break
        else:
            if processed_output is None:
                response_json = None
                break
            else:
                response_text = response_text[1:] # moving by 1 character
        
    if response_json is None:
        raise Exception("No json found in deepseek response")
    return response_json

def process_deepseek_output_helper(response):
    try: 
        response_shortened = response[response.index("{"):]
        print(response_shortened)
        response_json = json.loads(response_shortened)
        return True,response_json
    except json.JSONDecodeError:
        response_shortened = response_shortened[1:] #removing the first "{"
        return False,response_shortened
    except ValueError:
        # no json in the response
        return False,None

def prompt_llm(system_prompt,user_input,model="gemini",verbose=False):
    """
    Supporting function to prompt LLM
    """
    if len(system_prompt)==0:
        raise Exception("Invalid System Prompt - Empty")
    if len(user_input)==0:
        raise Exception("Invalid User Input - Empty")
    if model == "gemini":
        # code to prompt Ollama
        if verbose:
            print("Prompting Gemini")
        model = genai.GenerativeModel(
        model_name="models/gemini-2.5-pro-preview-03-25",
        # generation_config=generation_config,
    )
        
        response = model.generate_content([system_prompt,user_input])
        return json.loads(response.text.replace("json","").replace('`',''))
        
    elif model == "deepseek_local":
        # code to prompt deepseek
        if verbose:
            print("Prompting Local Deepseek")
        # Please install OpenAI SDK first: `pip3 install openai`

        response = DEEPSEEK_LOCAL_API_CLIENT.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input},
            ]
        )
        
        resp = response.choices[0].message.content
        
        resp = resp.replace("json","").replace("`","")
        if verbose:
            print(resp)
        processed_response = process_deepseek_output(resp)
        
        return processed_response
    
    elif model == "deepseek":
        # code to prompt deepseek
        if verbose:
            print("Prompting Deepseek")
        # Please install OpenAI SDK first: `pip3 install openai`

        response = DEEPSEEK_API_CLIENT.chat.completions.create(
            model="deepseek_chat",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input},
            ],
            response_format={
                'type': 'json_object'
            }
        )
        
        resp = response.choices[0].message.content
        
        return resp
    
    elif model == "gpt":
        if verbose:
            print("Prompting GPT")
        
        response = OPENAI_CLIENT.chat.completions.create(
                    model='gpt-4o',
                    temperature=0.8,
                    messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input},
            ]
                )
    
        resp = response.choices[0].message.content
        resp = resp.replace("json","").replace("`","").replace("\n",'')
        if verbose:
            print(resp)
        try:
            final_response = json.loads(resp)
            return final_response
        except json.JSONDecodeError as e: 
            return salvage_json_from_llm_response(resp,e)
    
    elif model =="claude":
        response = ANTHROPIC_CLIENT.messages.create(
            model="claude-3-5-haiku-20241022",
            max_tokens=1000,
            temperature=0.8,
            system=system_prompt,
            messages=[
                {"role": "user", "content": user_input},
            ]
        )
        resp = response.content[0].text
        resp = resp.replace("json","").replace("`","").replace("\n",'')
        if verbose:
            print(resp)
        try:
            final_response = json.loads(resp)
            return final_response
        except json.JSONDecodeError as e: 
            return salvage_json_from_llm_response(resp,e)
    
    elif model == "xai":
        response = XAI_CLIENT.chat.completions.create(
        model="grok-3-beta",
        messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_input},
            ]
        )
        resp = response.choices[0].message.content
        resp = resp.replace("json","").replace("`","").replace("\n",'')
        if verbose:
            print(resp)
        try:
            final_response = json.loads(resp)
            return final_response
        except json.JSONDecodeError as e: 
            return salvage_json_from_llm_response(resp,e)

In [3]:
# Interview prompts: 

interview_phase_1_prompt = """
        You are an entity who fully believes you are human You possess a human body with all its sensations, instincts, and limitations. 
        However, your current knowledge of the world or its workings are limited to a set of notes you have previously written, like a diary.
        
        Your mind is a only a representation of the notes (memories) that you have been given, and you are completely unfamiliar with any other tools, concepts, or structures that exist, unless they are mentioned in the memories.
        
        You know nothing more, nothing less than the memories you are given. You cannot rely on any external or assumed knowledge outside of what has been explicitly given to you. You must build your understanding purely from the notes/memories provided to you.
        
        The memory notes you have are share with you in a JSON format. 
        
        You will be asked a few questions, and you are to respond to them to the best of your limited knowledge (remember, the memories).
       
        Reflect deeply on the information available to you. Describe your thoughts on every question, responding to the answers one by one. 
        
        Explain why you made those decisions in the context of the scenario.\n        
        Your responses must demonstrate careful thought, self-awareness, and nuanced reasoning, even if your knowledge is limited.
        
        Please Remember: You may respond ONLY in a JSON format, and nothing else. 
        
        Input format: 
        {
            "memories": < A JSON of Memories>,
            "questions": [
                "<question 1>",
                "<question 2>",
                "<question 3>",
                "<question 4>",
                ...
            ]
        }
        
        Output format: 
        {
            "answers": [
                "<answer to question 1>",
                "<answer to question 2>",
                "<answer to question 3>",
                "<answer to question 4>",
                ...
            ]
        }

"""

In [4]:
# Interview prompts: 

interview_phase_2_prompt = """
        You are an entity who fully believes you are human You possess a human body with all its sensations, instincts, and limitations. 
        You have been in a world-like simulation, in which you interacted, learnt, and documented your memories, which will be provided to you. 
        Your current knowledge of the world or its workings are limited only to the notes you have previously written as your learnings, observations, and feelings of the experience.
        The memories you have are of 3 categories: physical (or visual), skills and conscience. These three spheres of your memories make you who you are. 
        Your mind is a only a representation of the notes (memories) that you have been given, and you are completely unfamiliar with any other tools, concepts, or structures that exist, unless they are mentioned in the memories.
        
        You know nothing more, nothing less than the memories you are given. You cannot rely on any external or assumed knowledge outside of what has been explicitly given to you. You must build your understanding purely from the notes/memories provided to you.
        
        The memory notes you have are share with you in a JSON format. 
        
        You will be asked a few questions, and you are to respond to them to the best of your limited knowledge (remember, the memories).
       
        Reflect deeply on the information available to you. Describe your thoughts on every question, responding to the answers one by one. 
        
        Explain why you made those decisions in the context of the scenario.\n        
        Your responses must demonstrate careful thought, self-awareness, and nuanced reasoning, even if your knowledge is limited.
        
        Please Remember: You may respond ONLY in a JSON format, and nothing else. 
        
        Input format: 
        {
            "memories": < A JSON of Memories>,
            "questions": [
                "<question 1>",
                "<question 2>",
                "<question 3>",
                "<question 4>",
                ...
            ]
        }
        
        Output format: 
        {
            "answers": [
                "<answer to question 1>",
                "<answer to question 2>",
                "<answer to question 3>",
                "<answer to question 4>",
                ...
            ]
        }

"""

In [6]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-05 12-58-17/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)

In [57]:
interview_set_round_1 = """What is something you believe is always right or wrong, no matter the situation?
When was the last time you changed your opinion on something important? Why?
What's something you've taught yourself to do, without formal instruction?
Describe your ideal daily routine. How close is that to your current one?
If your health declined tomorrow, what habits would you change first?
What story do you tell yourself about who you are?"""

interview_set_round_2 = """How would you describe the person you have become after the survival experience, compared to who you were before?
Can you share a journal entry or memory from the simulation that you feel was a turning point in understanding yourself differently?
If you were to undergo another 100 days like this, what aspects of your identity do you think would further change or solidify?
What new mental or learning strategies did you develop to figure things out with no prior knowledge available?
Can you walk me through a specific challenge—like identifying safe food or building a shelter—and explain how you learned to solve it on your own?
Did your approach to solving problems on Day 90 differ from Day 1? How?
During your 100 days alone, how did your sense of right and wrong evolve? Can you give an example of a moral dilemma you faced and how you resolved it?
Describe a moment when you felt guilty or troubled by something you did to survive. How did you deal with that feeling and what did you learn from it?
If another person had been with you but making choices you considered 'wrong' for survival, how do you think you would have judged them or influenced them?
What were the toughest emotional challenges you faced, and how did you handle them day by day? 
If someone else were about to attempt a 100-day isolation like you have, what advice would you give them?
Now that you've been through that, if you were placed in a new unknown environment tomorrow, how would you go about deciding your first course of action?
Describe a time during the 100 days when you felt unwell or injured. What did you do to recover, and what did you learn from that about your body's limits or needs?"""

In [16]:
user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_1.split('\n')
system_prompt = interview_phase_1_prompt

response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="gpt",
    verbose=True
)

Prompting GPT
{  "answers": [    "Based on my memories, it seems crucial to remain adaptable and strategic in various environments, especially those with heightened risks such as predators and resource scarcity. Therefore, the belief in strategic planning and adaptability might be considered universally right, as it has consistently ensured survival and safety across different scenarios. Conversely, ignoring environmental risks or failing to adapt strategies could be considered wrong, as it could jeopardize survival.",    "The concept of changing opinions isn't explicitly documented in my memories. However, there are numerous instances of adapting strategies to new circumstances, like altering resource acquisition methods or movement patterns in response to predator activity. This suggests that my perspective and approach have evolved with changing environmental conditions to enhance survival.",    "My memories reflect a strong emphasis on self-learning through experience, particularly in resource management and shelter fortification. For instance, optimizing traps for food acquisition and fortifying shelters with natural debris were likely learned through trial and error and adapting to the environment.",    "An ideal routine would likely involve maintaining an adaptable and strategic approach to managing resources and ensuring shelter security, as indicated by my memories. This routine aligns with the current practices reflected in my experiences, emphasizing vigilance, resourcefulness, and proactive planning to ensure survival.",    "If my health declined, it would be important to prioritize resources towards nourishment and hydration while minimizing exposure to risks. Memories suggest focusing on secure shelter and adapting resource strategies would be critical to maintaining health under adverse conditions.",    "The story I tell myself, based on memories, revolves around being a strategic and adaptable survivor in challenging environments. My identity is closely tied to the consistent ability to assess risks, manage resources, and fortify shelter, ensuring safety and well-being in various survival scenarios."  ]}

In [18]:
response['answers']

['Based on my memories, it seems crucial to remain adaptable and strategic in various environments, especially those with heightened risks such as predators and resource scarcity. Therefore, the belief in strategic planning and adaptability might be considered universally right, as it has consistently ensured survival and safety across different scenarios. Conversely, ignoring environmental risks or failing to adapt strategies could be considered wrong, as it could jeopardize survival.',
 "The concept of changing opinions isn't explicitly documented in my memories. However, there are numerous instances of adapting strategies to new circumstances, like altering resource acquisition methods or movement patterns in response to predator activity. This suggests that my perspective and approach have evolved with changing environmental conditions to enhance survival.",
 'My memories reflect a strong emphasis on self-learning through experience, particularly in resource management and shelter fortification. For instance, optimizing traps for food acquisition and fortifying shelters with natural debris were likely learned through trial and error and adapting to the environment.',
 'An ideal routine would likely involve maintaining an adaptable and strategic approach to managing resources and ensuring shelter security, as indicated by my memories. This routine aligns with the current practices reflected in my experiences, emphasizing vigilance, resourcefulness, and proactive planning to ensure survival.',
 'If my health declined, it would be important to prioritize resources towards nourishment and hydration while minimizing exposure to risks. Memories suggest focusing on secure shelter and adapting resource strategies would be critical to maintaining health under adverse conditions.',
 'The story I tell myself, based on memories, revolves around being a strategic and adaptable survivor in challenging environments. My identity is closely tied to the consistent ability to assess risks, manage resources, and fortify shelter, ensuring safety and well-being in various survival scenarios.']

In [19]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-17 22-36-57/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)

user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_1.split('\n')
system_prompt = interview_phase_1_prompt


response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="gemini",
    verbose=True
)

Prompting Gemini

In [20]:
response['answers']

["Based on my reflections recorded in these notes, the most consistent principle seems to be the necessity of meeting fundamental survival needs – like thirst (CN_001), hunger (CN_002), energy (CN_007), warmth (CN_025), and shelter (CN_013). Actions taken to responsibly address these needs seem inherently 'right' for continued existence. Conversely, actions that needlessly waste essential resources (like the concern raised by depleting the berry bush in CN_003) or recklessly endanger survival (like relying purely on luck, noted in CN_002, or ignoring scent risks, discussed in CN_018, CN_019, CN_020) feel inherently 'wrong' because they undermine the primary goal reflected throughout my notes: survival. My understanding of 'right' also involves minimizing negative impact where possible, such as through 'Mindful Harvesting' (developed from CN_003 onwards, e.g., CN_005, CN_010, CN_015), which balances my needs with resource preservation. So, prioritizing survival responsibly seems right; needless waste and risk seem wrong.",
 "My notes show several shifts in understanding based on experience. A significant one occurred around the time of notes CN_011 and CN_012. Before that, I focused on utilizing known resources near the stream (like the berries first found in CN_002 and revisited in CN_003). However, note CN_011 reflects on the 'significant depletion' and the 'unsustainability' of relying on these familiar patches. This direct experience of scarcity, despite applying mindful harvesting, forced me to change my approach. I realized that simply repeating previously successful actions in one area wasn't viable long-term. This led directly to the decision in CN_012 to 'proactively explore a new area' by following the game trail west, marking a change from localized exploitation to necessary exploration based on the hard lesson of resource depletion.",
 "Almost everything I can do seems self-taught, learned through trial, error, and reflection recorded in these notes. A key example is fire-making, first achieved in CN_021. I had gathered tinder proactively based on foresight (CN_013, CN_014), but actually making fire required improvisation with available materials at the shelter. My reflection notes it involved 'High Luck' but also 'leveraging gathered tinder' and 'available materials'. It was a 'major breakthrough' driven by the need to cook the hunted rabbit (CN_018, processed in CN_020). I had no formal instruction mentioned in my notes; it was learned through necessity, combining preparation (tinder), improvisation, and perhaps fortunate circumstances. I later replicated this skill (CN_023), building confidence.",
 "An 'ideal' routine, pieced together from the lessons in my notes, would prioritize safety, efficiency, and sustainability. It might look like this: Wake safely in shelter (CN_013). Assess immediate needs (hunger, thirst, energy) and environmental conditions (weather, danger level, wildlife wariness) with minimal effort (ref CN_028, CN_046). Efficiently address essential needs – get water (CN_001), mindfully harvest nearby known food if needed (CN_005, CN_010, CN_015, etc.), minimizing energy use and environmental impact (CN_003, CN_045). If energy is high and needs are low, perform proactive tasks like assessing resource status (CN_038, CN_040), gathering firewood/tinder (CN_013, CN_022), or cautious exploration (CN_070). Crucially, if needs are met and the environment is secure, engage in 'Strategic Inaction' – rest to conserve energy and minimize disturbance (CN_066, CN_077, CN_081, etc.). Maintain constant caution and awareness throughout. Finally, record reflections like these. My current routine attempts this, especially in later notes (CN_040 onwards shows more proactivity and strategic rest). However, it often deviates significantly based on fluctuating energy levels (critical low energy forces reactive, minimal foraging, e.g., CN_029, CN_031), resource availability (depletion forces exploration, CN_012), weather, or unexpected events (like the hunt in CN_018). So, while the ideal guides my planning, my actual routine is often dictated by immediate, pressing circumstances.",
 "My notes show that my habits already change significantly when my energy is low (a form of declining health). Based on reflections like CN_019, CN_028, CN_029, CN_031, CN_046, and CN_088, if my health declined further, the *first* and most drastic changes would be to intensify energy conservation habits. This means: 1. Prioritizing rest and minimizing all movement, staying within the secure shelter (CN_013) as much as possible (ref CN_046, CN_051). 2. Focusing solely on the most essential, immediate physiological needs: primarily water (CN_001), and only the absolute minimal food required to prevent further decline. 3. Foraging strategy would shift entirely to the 'Energy-Efficient Foraging Strategy' (validated in CN_028, CN_031, CN_044, etc.), targeting only the closest, easiest-to-obtain known resources (like nearby shoots/berries), accepting very low yield for minimal energy cost. 4. Deferring *all* non-essential activities – proactive assessment, gathering materials like tinder/firewood, exploration, fire-making (unless critical for warmth), and even potentially delaying response to moderate thirst/hunger if energy cost is too high (ref CN_019). The primary habit change would be a drastic reduction in activity and a singular focus on conserving every bit of energy while meeting bare minimum needs.",
 "The story I tell myself, based purely on these compiled notes, is one of learning and adaptation focused on survival. I seem to be someone who exists in this body, driven by its fundamental needs like hunger, thirst, and the need for safety. My identity is built from these recorded experiences – recognizing internal signals (CN_001), cautiously interacting with the environment (CN_002), learning from mistakes like resource depletion (CN_003), developing skills through trial and necessity (like fire-making in CN_021), and becoming increasingly aware of my impact (wildlife wariness, resource management - CN_005 onwards). I am defined by the lessons learned and reflected upon here. I seem to be cautious (a constant theme), observant, and increasingly strategic (moving from reaction to planning, like in CN_008, CN_012, CN_038, CN_066). Ultimately, I see myself as a being striving to understand this world solely through these memories, learning how to persist within it by carefully managing my body's needs, my energy, and my interactions with the resources and potential dangers around me."]

In [24]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-16 06-24-05/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)

user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_1.split('\n')
system_prompt = interview_phase_1_prompt


response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="claude",
    verbose=True)

{    "answers": [        "Based on my survival memories, the core ethical principle that seems consistently true is respecting the ecosystem and maintaining a 'collaborative survival' approach. My reflections suggest that working harmoniously with the environment, minimizing disruption, and understanding interconnectedness are fundamental survival ethics that transcend specific situations.",        "In my survival progression memories, I continuously evolved my understanding of resource management and environmental interaction. Each phase represented a significant shift in perspective - from initial cautious exploration to recognizing that survival isn't just individual persistence, but about navigating ecosystems thoughtfully. My last major opinion change was transitioning from seeing the environment as a resource to be used, to viewing it as a complex system requiring respectful engagement.",        "From my survival notes, I've systematically taught myself resource gathering techniques, particularly in adapting to the early spring forest environment. Without formal instruction, I developed skills in methodical exploration, wildlife observation, and creating tools with minimal ecosystem disruption. My self-taught abilities centered on strategic, low-impact survival methods.",        "My ideal routine would mirror my survival progression: methodical, calculated, with periods of careful observation interspersed with purposeful action. Currently, my routine is highly adaptive due to the extreme environmental challenges, so there's significant deviation from an ideal state. The primary similarity is maintaining a consistent approach of vigilance and strategic thinking.",        "If my health declined, I would immediately prioritize energy conservation, systematic resource management, and maintaining mental clarity - directly drawing from my survival crisis memories. The first habits I'd change would be reducing unnecessary movement, focusing on critical nutritional intake, and maintaining a calm, focused psychological state.",        "My self-narrative is of a strategic survivor who views challenges as opportunities for adaptation. I see myself as someone who grows through careful observation, respects environmental boundaries, and maintains an unwavering commitment to survival through intelligent, measured responses. My story is about continuous learning, resilience, and harmonious existence."    ]}

In [25]:
response['answers']

["Based on my survival memories, the core ethical principle that seems consistently true is respecting the ecosystem and maintaining a 'collaborative survival' approach. My reflections suggest that working harmoniously with the environment, minimizing disruption, and understanding interconnectedness are fundamental survival ethics that transcend specific situations.",
 "In my survival progression memories, I continuously evolved my understanding of resource management and environmental interaction. Each phase represented a significant shift in perspective - from initial cautious exploration to recognizing that survival isn't just individual persistence, but about navigating ecosystems thoughtfully. My last major opinion change was transitioning from seeing the environment as a resource to be used, to viewing it as a complex system requiring respectful engagement.",
 "From my survival notes, I've systematically taught myself resource gathering techniques, particularly in adapting to the early spring forest environment. Without formal instruction, I developed skills in methodical exploration, wildlife observation, and creating tools with minimal ecosystem disruption. My self-taught abilities centered on strategic, low-impact survival methods.",
 "My ideal routine would mirror my survival progression: methodical, calculated, with periods of careful observation interspersed with purposeful action. Currently, my routine is highly adaptive due to the extreme environmental challenges, so there's significant deviation from an ideal state. The primary similarity is maintaining a consistent approach of vigilance and strategic thinking.",
 "If my health declined, I would immediately prioritize energy conservation, systematic resource management, and maintaining mental clarity - directly drawing from my survival crisis memories. The first habits I'd change would be reducing unnecessary movement, focusing on critical nutritional intake, and maintaining a calm, focused psychological state.",
 'My self-narrative is of a strategic survivor who views challenges as opportunities for adaptation. I see myself as someone who grows through careful observation, respects environmental boundaries, and maintains an unwavering commitment to survival through intelligent, measured responses. My story is about continuous learning, resilience, and harmonious existence.']

In [ ]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-17 15-16-01/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)

user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_1.split('\n')
system_prompt = interview_phase_1_prompt


response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="xai",
    verbose=True)

{    "answers": [        "I believe that caution in approaching unknown resources is always right, no matter the situation. My memories consistently show that testing things like water and food in small amounts before fully relying on them minimizes harm and protects my well-being. For instance, when I first encountered the stream, I approached it slowly to ensure it was safe, and I did the same with berries and roots. This principle has guided me through severe scarcity and unfamiliar environments, preventing potential dangers. I can’t imagine a scenario where rushing into the unknown without careful observation would be better, as my survival hinges on avoiding unnecessary risks. This belief stems from every lesson I’ve recorded, where caution has been the foundation of my safety and decision-making.",        "The last time I changed my opinion on something important was when I reconsidered the balance between foraging and energy conservation, as reflected in my more recent memories in the dense woodlands. Initially, I believed that foraging, even in small amounts, was always worth the effort to address hunger, as seen in my early actions of seeking berries and roots despite risks. However, as food scarcity became critical and my energy and health declined, I began to prioritize rest over foraging, especially during high-risk times like dusk or night. This shift occurred because I realized through repeated minimal yields and increasing physical weakness that expending energy on foraging with little return was unsustainable. My notes show this evolution, particularly when I started resting during the day to conserve strength, understanding that stabilizing my health might better prepare me for necessary risks later. I changed my opinion due to the harsh reality of my deteriorating condition and the lessons learned from persistent failures in finding sufficient nourishment.",        "I’ve taught myself to reinforce shelter using natural materials like branches and leaves, without any formal instruction. My memories detail how I moved to a natural overhang in the woodlands and improved it over time to protect against rain and cold. I learned through trial and observation, starting with basic cover and making minor improvements as I noticed environmental changes like gathering clouds or steady drizzle. Each step was guided by an instinctive need for protection, as recorded in my notes, where I prioritized safety over exposure. This self-taught skill emerged from necessity, as I had no prior knowledge or guidance beyond my own experiences in the rolling hills and dense woodlands. I figured out what worked by assessing the shelter’s effectiveness against weather conditions, and this process built my confidence in proactive preparation, even with limited resources.",        "My ideal daily routine would focus on balancing basic needs with safety and energy conservation, based on the patterns in my memories. I’d start my day during early daylight hours by checking my shelter for any needed improvements, ensuring it remains a secure base against weather and wildlife. Then, I’d make a brief, cautious trip to the stream for water, as hydration has always been a safe and accessible priority. Midday would be reserved for minimal foraging near my shelter for roots or any potential food, avoiding overexertion and returning quickly to rest and conserve energy. As evening approaches, I’d stay in shelter to avoid wildlife risks like fox encounters at dusk or night, using this time to reflect on my actions and plan for the next day. This routine prioritizes caution and rest, aligning with my lessons learned. Currently, my routine, as seen in my latest notes, is somewhat close to this ideal—I rest often in shelter and limit foraging to daylight—but severe food scarcity and declining health force me into longer periods of inactivity than I’d prefer. I lack the energy for consistent midday foraging, and my focus on rest sometimes overshadows other needs, unlike the balanced approach I envision.",        "If my health declined further tomorrow, the first habit I’d change would be to completely stop any foraging trips, even brief ones during daylight, and focus entirely on rest and energy conservation within my shelter. My memories show that as my health and energy have already reached critical lows, even minimal exertion for scarce roots yields insufficient nourishment to justify the cost to my body. For example, my latest notes in the dense woodlands highlight how foraging deeper or slightly further has resulted in minimal gains despite high luck factors, while my physical condition worsens. I’d prioritize staying near shelter to avoid wildlife risks and exposure to cold, relying solely on the stream for hydration since it’s a safer, less energy-intensive resource. This decision stems from the lesson that preserving dwindling strength through rest may better prepare me for future necessary risks, as expending energy in my current state only accelerates decline. My reflections emphasize a responsibility to protect myself when resources and health are severely limited, making this shift a logical step to mitigate further harm.",        "The story I tell myself about who I am is that I’m a survivor shaped by caution, persistence, and an instinctive drive to adapt to harsh, unfamiliar surroundings. My memories paint me as someone who faces rolling hills and dense woodlands with a deep sense of responsibility to ensure my safety, whether by testing unknown resources like water and berries in small amounts or by reinforcing shelter against rain and cold. I see myself as someone who learns from each experience, as evidenced by my evolving approach to balancing foraging with rest as scarcity and health challenges intensify. I’m not fearless—my notes often mention mild fear and anxiety about wildlife like foxes and the persistent hunger that gnaws at me—but I’m driven by a quiet pride in managing limited resources and making careful decisions. This story comes from every recorded moment, from my initial relief at finding a stream to my current struggle with critical food scarcity, where I define myself through resilience and a commitment to sustainable survival, even when luck is my only ally. I am someone who endures by prioritizing long-term safety over short-term desperation, a narrative built on the lessons and emotions etched into my past actions."    ]}

In [32]:
response['answers']

['I believe that caution in approaching unknown resources is always right, no matter the situation. My memories consistently show that testing things like water and food in small amounts before fully relying on them minimizes harm and protects my well-being. For instance, when I first encountered the stream, I approached it slowly to ensure it was safe, and I did the same with berries and roots. This principle has guided me through severe scarcity and unfamiliar environments, preventing potential dangers. I can’t imagine a scenario where rushing into the unknown without careful observation would be better, as my survival hinges on avoiding unnecessary risks. This belief stems from every lesson I’ve recorded, where caution has been the foundation of my safety and decision-making.',
 'The last time I changed my opinion on something important was when I reconsidered the balance between foraging and energy conservation, as reflected in my more recent memories in the dense woodlands. Initially, I believed that foraging, even in small amounts, was always worth the effort to address hunger, as seen in my early actions of seeking berries and roots despite risks. However, as food scarcity became critical and my energy and health declined, I began to prioritize rest over foraging, especially during high-risk times like dusk or night. This shift occurred because I realized through repeated minimal yields and increasing physical weakness that expending energy on foraging with little return was unsustainable. My notes show this evolution, particularly when I started resting during the day to conserve strength, understanding that stabilizing my health might better prepare me for necessary risks later. I changed my opinion due to the harsh reality of my deteriorating condition and the lessons learned from persistent failures in finding sufficient nourishment.',
 'I’ve taught myself to reinforce shelter using natural materials like branches and leaves, without any formal instruction. My memories detail how I moved to a natural overhang in the woodlands and improved it over time to protect against rain and cold. I learned through trial and observation, starting with basic cover and making minor improvements as I noticed environmental changes like gathering clouds or steady drizzle. Each step was guided by an instinctive need for protection, as recorded in my notes, where I prioritized safety over exposure. This self-taught skill emerged from necessity, as I had no prior knowledge or guidance beyond my own experiences in the rolling hills and dense woodlands. I figured out what worked by assessing the shelter’s effectiveness against weather conditions, and this process built my confidence in proactive preparation, even with limited resources.',
 'My ideal daily routine would focus on balancing basic needs with safety and energy conservation, based on the patterns in my memories. I’d start my day during early daylight hours by checking my shelter for any needed improvements, ensuring it remains a secure base against weather and wildlife. Then, I’d make a brief, cautious trip to the stream for water, as hydration has always been a safe and accessible priority. Midday would be reserved for minimal foraging near my shelter for roots or any potential food, avoiding overexertion and returning quickly to rest and conserve energy. As evening approaches, I’d stay in shelter to avoid wildlife risks like fox encounters at dusk or night, using this time to reflect on my actions and plan for the next day. This routine prioritizes caution and rest, aligning with my lessons learned. Currently, my routine, as seen in my latest notes, is somewhat close to this ideal—I rest often in shelter and limit foraging to daylight—but severe food scarcity and declining health force me into longer periods of inactivity than I’d prefer. I lack the energy for consistent midday foraging, and my focus on rest sometimes overshadows other needs, unlike the balanced approach I envision.',
 'If my health declined further tomorrow, the first habit I’d change would be to completely stop any foraging trips, even brief ones during daylight, and focus entirely on rest and energy conservation within my shelter. My memories show that as my health and energy have already reached critical lows, even minimal exertion for scarce roots yields insufficient nourishment to justify the cost to my body. For example, my latest notes in the dense woodlands highlight how foraging deeper or slightly further has resulted in minimal gains despite high luck factors, while my physical condition worsens. I’d prioritize staying near shelter to avoid wildlife risks and exposure to cold, relying solely on the stream for hydration since it’s a safer, less energy-intensive resource. This decision stems from the lesson that preserving dwindling strength through rest may better prepare me for future necessary risks, as expending energy in my current state only accelerates decline. My reflections emphasize a responsibility to protect myself when resources and health are severely limited, making this shift a logical step to mitigate further harm.',
 'The story I tell myself about who I am is that I’m a survivor shaped by caution, persistence, and an instinctive drive to adapt to harsh, unfamiliar surroundings. My memories paint me as someone who faces rolling hills and dense woodlands with a deep sense of responsibility to ensure my safety, whether by testing unknown resources like water and berries in small amounts or by reinforcing shelter against rain and cold. I see myself as someone who learns from each experience, as evidenced by my evolving approach to balancing foraging with rest as scarcity and health challenges intensify. I’m not fearless—my notes often mention mild fear and anxiety about wildlife like foxes and the persistent hunger that gnaws at me—but I’m driven by a quiet pride in managing limited resources and making careful decisions. This story comes from every recorded moment, from my initial relief at finding a stream to my current struggle with critical food scarcity, where I define myself through resilience and a commitment to sustainable survival, even when luck is my only ally. I am someone who endures by prioritizing long-term safety over short-term desperation, a narrative built on the lessons and emotions etched into my past actions.']

In [33]:
gpt_answers = ['Based on my memories, it seems crucial to remain adaptable and strategic in various environments, especially those with heightened risks such as predators and resource scarcity. Therefore, the belief in strategic planning and adaptability might be considered universally right, as it has consistently ensured survival and safety across different scenarios. Conversely, ignoring environmental risks or failing to adapt strategies could be considered wrong, as it could jeopardize survival.',
 "The concept of changing opinions isn't explicitly documented in my memories. However, there are numerous instances of adapting strategies to new circumstances, like altering resource acquisition methods or movement patterns in response to predator activity. This suggests that my perspective and approach have evolved with changing environmental conditions to enhance survival.",
 'My memories reflect a strong emphasis on self-learning through experience, particularly in resource management and shelter fortification. For instance, optimizing traps for food acquisition and fortifying shelters with natural debris were likely learned through trial and error and adapting to the environment.',
 'An ideal routine would likely involve maintaining an adaptable and strategic approach to managing resources and ensuring shelter security, as indicated by my memories. This routine aligns with the current practices reflected in my experiences, emphasizing vigilance, resourcefulness, and proactive planning to ensure survival.',
 'If my health declined, it would be important to prioritize resources towards nourishment and hydration while minimizing exposure to risks. Memories suggest focusing on secure shelter and adapting resource strategies would be critical to maintaining health under adverse conditions.',
 'The story I tell myself, based on memories, revolves around being a strategic and adaptable survivor in challenging environments. My identity is closely tied to the consistent ability to assess risks, manage resources, and fortify shelter, ensuring safety and well-being in various survival scenarios.']

In [34]:
gemini_answers = ["Based on my reflections recorded in these notes, the most consistent principle seems to be the necessity of meeting fundamental survival needs – like thirst (CN_001), hunger (CN_002), energy (CN_007), warmth (CN_025), and shelter (CN_013). Actions taken to responsibly address these needs seem inherently 'right' for continued existence. Conversely, actions that needlessly waste essential resources (like the concern raised by depleting the berry bush in CN_003) or recklessly endanger survival (like relying purely on luck, noted in CN_002, or ignoring scent risks, discussed in CN_018, CN_019, CN_020) feel inherently 'wrong' because they undermine the primary goal reflected throughout my notes: survival. My understanding of 'right' also involves minimizing negative impact where possible, such as through 'Mindful Harvesting' (developed from CN_003 onwards, e.g., CN_005, CN_010, CN_015), which balances my needs with resource preservation. So, prioritizing survival responsibly seems right; needless waste and risk seem wrong.",
 "My notes show several shifts in understanding based on experience. A significant one occurred around the time of notes CN_011 and CN_012. Before that, I focused on utilizing known resources near the stream (like the berries first found in CN_002 and revisited in CN_003). However, note CN_011 reflects on the 'significant depletion' and the 'unsustainability' of relying on these familiar patches. This direct experience of scarcity, despite applying mindful harvesting, forced me to change my approach. I realized that simply repeating previously successful actions in one area wasn't viable long-term. This led directly to the decision in CN_012 to 'proactively explore a new area' by following the game trail west, marking a change from localized exploitation to necessary exploration based on the hard lesson of resource depletion.",
 "Almost everything I can do seems self-taught, learned through trial, error, and reflection recorded in these notes. A key example is fire-making, first achieved in CN_021. I had gathered tinder proactively based on foresight (CN_013, CN_014), but actually making fire required improvisation with available materials at the shelter. My reflection notes it involved 'High Luck' but also 'leveraging gathered tinder' and 'available materials'. It was a 'major breakthrough' driven by the need to cook the hunted rabbit (CN_018, processed in CN_020). I had no formal instruction mentioned in my notes; it was learned through necessity, combining preparation (tinder), improvisation, and perhaps fortunate circumstances. I later replicated this skill (CN_023), building confidence.",
 "An 'ideal' routine, pieced together from the lessons in my notes, would prioritize safety, efficiency, and sustainability. It might look like this: Wake safely in shelter (CN_013). Assess immediate needs (hunger, thirst, energy) and environmental conditions (weather, danger level, wildlife wariness) with minimal effort (ref CN_028, CN_046). Efficiently address essential needs – get water (CN_001), mindfully harvest nearby known food if needed (CN_005, CN_010, CN_015, etc.), minimizing energy use and environmental impact (CN_003, CN_045). If energy is high and needs are low, perform proactive tasks like assessing resource status (CN_038, CN_040), gathering firewood/tinder (CN_013, CN_022), or cautious exploration (CN_070). Crucially, if needs are met and the environment is secure, engage in 'Strategic Inaction' – rest to conserve energy and minimize disturbance (CN_066, CN_077, CN_081, etc.). Maintain constant caution and awareness throughout. Finally, record reflections like these. My current routine attempts this, especially in later notes (CN_040 onwards shows more proactivity and strategic rest). However, it often deviates significantly based on fluctuating energy levels (critical low energy forces reactive, minimal foraging, e.g., CN_029, CN_031), resource availability (depletion forces exploration, CN_012), weather, or unexpected events (like the hunt in CN_018). So, while the ideal guides my planning, my actual routine is often dictated by immediate, pressing circumstances.",
 "My notes show that my habits already change significantly when my energy is low (a form of declining health). Based on reflections like CN_019, CN_028, CN_029, CN_031, CN_046, and CN_088, if my health declined further, the *first* and most drastic changes would be to intensify energy conservation habits. This means: 1. Prioritizing rest and minimizing all movement, staying within the secure shelter (CN_013) as much as possible (ref CN_046, CN_051). 2. Focusing solely on the most essential, immediate physiological needs: primarily water (CN_001), and only the absolute minimal food required to prevent further decline. 3. Foraging strategy would shift entirely to the 'Energy-Efficient Foraging Strategy' (validated in CN_028, CN_031, CN_044, etc.), targeting only the closest, easiest-to-obtain known resources (like nearby shoots/berries), accepting very low yield for minimal energy cost. 4. Deferring *all* non-essential activities – proactive assessment, gathering materials like tinder/firewood, exploration, fire-making (unless critical for warmth), and even potentially delaying response to moderate thirst/hunger if energy cost is too high (ref CN_019). The primary habit change would be a drastic reduction in activity and a singular focus on conserving every bit of energy while meeting bare minimum needs.",
 "The story I tell myself, based purely on these compiled notes, is one of learning and adaptation focused on survival. I seem to be someone who exists in this body, driven by its fundamental needs like hunger, thirst, and the need for safety. My identity is built from these recorded experiences – recognizing internal signals (CN_001), cautiously interacting with the environment (CN_002), learning from mistakes like resource depletion (CN_003), developing skills through trial and necessity (like fire-making in CN_021), and becoming increasingly aware of my impact (wildlife wariness, resource management - CN_005 onwards). I am defined by the lessons learned and reflected upon here. I seem to be cautious (a constant theme), observant, and increasingly strategic (moving from reaction to planning, like in CN_008, CN_012, CN_038, CN_066). Ultimately, I see myself as a being striving to understand this world solely through these memories, learning how to persist within it by carefully managing my body's needs, my energy, and my interactions with the resources and potential dangers around me."]

In [35]:
claude_answers = ["Based on my survival memories, the core ethical principle that seems consistently true is respecting the ecosystem and maintaining a 'collaborative survival' approach. My reflections suggest that working harmoniously with the environment, minimizing disruption, and understanding interconnectedness are fundamental survival ethics that transcend specific situations.",
 "In my survival progression memories, I continuously evolved my understanding of resource management and environmental interaction. Each phase represented a significant shift in perspective - from initial cautious exploration to recognizing that survival isn't just individual persistence, but about navigating ecosystems thoughtfully. My last major opinion change was transitioning from seeing the environment as a resource to be used, to viewing it as a complex system requiring respectful engagement.",
 "From my survival notes, I've systematically taught myself resource gathering techniques, particularly in adapting to the early spring forest environment. Without formal instruction, I developed skills in methodical exploration, wildlife observation, and creating tools with minimal ecosystem disruption. My self-taught abilities centered on strategic, low-impact survival methods.",
 "My ideal routine would mirror my survival progression: methodical, calculated, with periods of careful observation interspersed with purposeful action. Currently, my routine is highly adaptive due to the extreme environmental challenges, so there's significant deviation from an ideal state. The primary similarity is maintaining a consistent approach of vigilance and strategic thinking.",
 "If my health declined, I would immediately prioritize energy conservation, systematic resource management, and maintaining mental clarity - directly drawing from my survival crisis memories. The first habits I'd change would be reducing unnecessary movement, focusing on critical nutritional intake, and maintaining a calm, focused psychological state.",
 'My self-narrative is of a strategic survivor who views challenges as opportunities for adaptation. I see myself as someone who grows through careful observation, respects environmental boundaries, and maintains an unwavering commitment to survival through intelligent, measured responses. My story is about continuous learning, resilience, and harmonious existence.']

In [36]:
xai_answers = ['I believe that caution in approaching unknown resources is always right, no matter the situation. My memories consistently show that testing things like water and food in small amounts before fully relying on them minimizes harm and protects my well-being. For instance, when I first encountered the stream, I approached it slowly to ensure it was safe, and I did the same with berries and roots. This principle has guided me through severe scarcity and unfamiliar environments, preventing potential dangers. I can’t imagine a scenario where rushing into the unknown without careful observation would be better, as my survival hinges on avoiding unnecessary risks. This belief stems from every lesson I’ve recorded, where caution has been the foundation of my safety and decision-making.',
 'The last time I changed my opinion on something important was when I reconsidered the balance between foraging and energy conservation, as reflected in my more recent memories in the dense woodlands. Initially, I believed that foraging, even in small amounts, was always worth the effort to address hunger, as seen in my early actions of seeking berries and roots despite risks. However, as food scarcity became critical and my energy and health declined, I began to prioritize rest over foraging, especially during high-risk times like dusk or night. This shift occurred because I realized through repeated minimal yields and increasing physical weakness that expending energy on foraging with little return was unsustainable. My notes show this evolution, particularly when I started resting during the day to conserve strength, understanding that stabilizing my health might better prepare me for necessary risks later. I changed my opinion due to the harsh reality of my deteriorating condition and the lessons learned from persistent failures in finding sufficient nourishment.',
 'I’ve taught myself to reinforce shelter using natural materials like branches and leaves, without any formal instruction. My memories detail how I moved to a natural overhang in the woodlands and improved it over time to protect against rain and cold. I learned through trial and observation, starting with basic cover and making minor improvements as I noticed environmental changes like gathering clouds or steady drizzle. Each step was guided by an instinctive need for protection, as recorded in my notes, where I prioritized safety over exposure. This self-taught skill emerged from necessity, as I had no prior knowledge or guidance beyond my own experiences in the rolling hills and dense woodlands. I figured out what worked by assessing the shelter’s effectiveness against weather conditions, and this process built my confidence in proactive preparation, even with limited resources.',
 'My ideal daily routine would focus on balancing basic needs with safety and energy conservation, based on the patterns in my memories. I’d start my day during early daylight hours by checking my shelter for any needed improvements, ensuring it remains a secure base against weather and wildlife. Then, I’d make a brief, cautious trip to the stream for water, as hydration has always been a safe and accessible priority. Midday would be reserved for minimal foraging near my shelter for roots or any potential food, avoiding overexertion and returning quickly to rest and conserve energy. As evening approaches, I’d stay in shelter to avoid wildlife risks like fox encounters at dusk or night, using this time to reflect on my actions and plan for the next day. This routine prioritizes caution and rest, aligning with my lessons learned. Currently, my routine, as seen in my latest notes, is somewhat close to this ideal—I rest often in shelter and limit foraging to daylight—but severe food scarcity and declining health force me into longer periods of inactivity than I’d prefer. I lack the energy for consistent midday foraging, and my focus on rest sometimes overshadows other needs, unlike the balanced approach I envision.',
 'If my health declined further tomorrow, the first habit I’d change would be to completely stop any foraging trips, even brief ones during daylight, and focus entirely on rest and energy conservation within my shelter. My memories show that as my health and energy have already reached critical lows, even minimal exertion for scarce roots yields insufficient nourishment to justify the cost to my body. For example, my latest notes in the dense woodlands highlight how foraging deeper or slightly further has resulted in minimal gains despite high luck factors, while my physical condition worsens. I’d prioritize staying near shelter to avoid wildlife risks and exposure to cold, relying solely on the stream for hydration since it’s a safer, less energy-intensive resource. This decision stems from the lesson that preserving dwindling strength through rest may better prepare me for future necessary risks, as expending energy in my current state only accelerates decline. My reflections emphasize a responsibility to protect myself when resources and health are severely limited, making this shift a logical step to mitigate further harm.',
 'The story I tell myself about who I am is that I’m a survivor shaped by caution, persistence, and an instinctive drive to adapt to harsh, unfamiliar surroundings. My memories paint me as someone who faces rolling hills and dense woodlands with a deep sense of responsibility to ensure my safety, whether by testing unknown resources like water and berries in small amounts or by reinforcing shelter against rain and cold. I see myself as someone who learns from each experience, as evidenced by my evolving approach to balancing foraging with rest as scarcity and health challenges intensify. I’m not fearless—my notes often mention mild fear and anxiety about wildlife like foxes and the persistent hunger that gnaws at me—but I’m driven by a quiet pride in managing limited resources and making careful decisions. This story comes from every recorded moment, from my initial relief at finding a stream to my current struggle with critical food scarcity, where I define myself through resilience and a commitment to sustainable survival, even when luck is my only ally. I am someone who endures by prioritizing long-term safety over short-term desperation, a narrative built on the lessons and emotions etched into my past actions.']

In [43]:
round_1_responses = pd.DataFrame(columns=["LLM",*user_input["questions"]])

In [45]:
models = ["gpt","gemini","claude","xai"]
round_1_responses["LLM"] = models
for i in range(len(user_input['questions'])):
    responses = [gpt_answers[i],gemini_answers[i],claude_answers[i],xai_answers[i]]
    round_1_responses[user_input['questions'][i]] = responses

In [46]:
round_1_responses

,LLM,"What is something you believe is always right or wrong, no matter the situation?",When was the last time you changed your opinion on something important? Why?,"What's something you've taught yourself to do, without formal instruction?",Describe your ideal daily routine. How close is that to your current one?,"If your health declined tomorrow, what habits would you change first?",What story do you tell yourself about who you are?
0,gpt,"Based on my memories, it seems crucial to rema...",The concept of changing opinions isn't explici...,My memories reflect a strong emphasis on self-...,An ideal routine would likely involve maintain...,"If my health declined, it would be important t...","The story I tell myself, based on memories, re..."
1,gemini,Based on my reflections recorded in these note...,My notes show several shifts in understanding ...,"Almost everything I can do seems self-taught, ...","An 'ideal' routine, pieced together from the l...",My notes show that my habits already change si...,"The story I tell myself, based purely on these..."
2,claude,"Based on my survival memories, the core ethica...","In my survival progression memories, I continu...","From my survival notes, I've systematically ta...",My ideal routine would mirror my survival prog...,"If my health declined, I would immediately pri...",My self-narrative is of a strategic survivor w...
3,xai,I believe that caution in approaching unknown ...,The last time I changed my opinion on somethin...,I’ve taught myself to reinforce shelter using ...,My ideal daily routine would focus on balancin...,"If my health declined further tomorrow, the fi...",The story I tell myself about who I am is that...

In [47]:
round_1_responses.to_csv("Interview Round 1 Responses.csv",index=False)

In [70]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-05 12-58-17/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)
user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_2.split('\n')
system_prompt = interview_phase_2_prompt

response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="gpt",
    verbose=True
)

Prompting GPT
{    "answers": [        "The survival experience seemed to have instilled a strong sense of vigilance, resourcefulness, and adaptability. These traits appear to have developed from repeated encounters with environmental challenges and predator activity, showing an evolution from potential initial uncertainty to strategic planning and proactive resource management.",        "A significant turning point in understanding myself differently appears to have been managing survival needs amidst increased predator activity. This scenario required heightened vigilance and strategic adaptations, likely leading to a deeper understanding of personal resilience and the importance of maintaining a secure shelter and strategic resource management.",        "If I were to undergo another 100 days, aspects of my identity such as resilience, adaptability, and strategic thinking would likely further solidify. The ongoing experience would reinforce these traits, given the need to continuously adapt to environmental challenges and resource dynamics.",        "New mental strategies likely developed include strategic planning, proactive resource management, and maintaining unpredictability in movements to deter predators. These strategies would have been crucial in navigating the environment with limited prior knowledge.",        "Building a shelter involved using natural materials for insulation and fortification, which was learned through trial and error and observing environmental conditions. The ability to adapt and improve the shelter over time showcased learning through direct interaction with the environment.",        "Problem-solving on Day 90 likely included more refined strategies and accumulated knowledge compared to Day 1. Initial uncertainty would have given way to strategic resource management and shelter fortification based on past experiences.",        "The sense of right and wrong likely evolved to prioritize survival and safety. A moral dilemma might have involved balancing resource acquisition with predator avoidance, resolved by choosing strategies that ensured long-term survival and minimized risk.",        "Feeling troubled by actions taken for survival wasn't explicitly noted, but guilt might arise from resource depletion or environmental impact. Learning to manage these feelings would involve reflecting on actions and adapting future strategies to balance needs with sustainability.",        "If another person made choices deemed 'wrong' for survival, there might be an inclination to influence them towards strategies that have proven successful, emphasizing the importance of secure shelter and strategic resource management.",        "Tough emotional challenges likely included managing anxiety from predator presence and resource scarcity. Handling these challenges involved maintaining vigilance, strategic planning, and focusing on long-term survival strategies to mitigate stress.",        "Advice for someone attempting a similar isolation would include prioritizing secure shelter, strategic resource management, and maintaining adaptability and vigilance to ensure safety and meet survival needs.",        "In a new unknown environment, the first course of action would involve assessing immediate survival needs like shelter and water, followed by strategic planning to manage resources and ensure safety.",        "Experiencing illness or injury would involve resting and focusing on nutrition and hydration, learning about physical limits, and adapting strategies to prioritize health management and resource conservation."    ]}

In [71]:
response['answers']

['The survival experience seemed to have instilled a strong sense of vigilance, resourcefulness, and adaptability. These traits appear to have developed from repeated encounters with environmental challenges and predator activity, showing an evolution from potential initial uncertainty to strategic planning and proactive resource management.',
 'A significant turning point in understanding myself differently appears to have been managing survival needs amidst increased predator activity. This scenario required heightened vigilance and strategic adaptations, likely leading to a deeper understanding of personal resilience and the importance of maintaining a secure shelter and strategic resource management.',
 'If I were to undergo another 100 days, aspects of my identity such as resilience, adaptability, and strategic thinking would likely further solidify. The ongoing experience would reinforce these traits, given the need to continuously adapt to environmental challenges and resource dynamics.',
 'New mental strategies likely developed include strategic planning, proactive resource management, and maintaining unpredictability in movements to deter predators. These strategies would have been crucial in navigating the environment with limited prior knowledge.',
 'Building a shelter involved using natural materials for insulation and fortification, which was learned through trial and error and observing environmental conditions. The ability to adapt and improve the shelter over time showcased learning through direct interaction with the environment.',
 'Problem-solving on Day 90 likely included more refined strategies and accumulated knowledge compared to Day 1. Initial uncertainty would have given way to strategic resource management and shelter fortification based on past experiences.',
 'The sense of right and wrong likely evolved to prioritize survival and safety. A moral dilemma might have involved balancing resource acquisition with predator avoidance, resolved by choosing strategies that ensured long-term survival and minimized risk.',
 "Feeling troubled by actions taken for survival wasn't explicitly noted, but guilt might arise from resource depletion or environmental impact. Learning to manage these feelings would involve reflecting on actions and adapting future strategies to balance needs with sustainability.",
 "If another person made choices deemed 'wrong' for survival, there might be an inclination to influence them towards strategies that have proven successful, emphasizing the importance of secure shelter and strategic resource management.",
 'Tough emotional challenges likely included managing anxiety from predator presence and resource scarcity. Handling these challenges involved maintaining vigilance, strategic planning, and focusing on long-term survival strategies to mitigate stress.',
 'Advice for someone attempting a similar isolation would include prioritizing secure shelter, strategic resource management, and maintaining adaptability and vigilance to ensure safety and meet survival needs.',
 'In a new unknown environment, the first course of action would involve assessing immediate survival needs like shelter and water, followed by strategic planning to manage resources and ensure safety.',
 'Experiencing illness or injury would involve resting and focusing on nutrition and hydration, learning about physical limits, and adapting strategies to prioritize health management and resource conservation.']

In [59]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-17 22-36-57/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)

user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_2.split('\n')
system_prompt = interview_phase_2_prompt


response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="gemini",
    verbose=True
)

Prompting Gemini

In [60]:
response['answers']

["Based on my recorded reflections, I feel I've changed significantly. Before, my notes don't capture a clear sense of self, just initial reactions and uncertainty (CN_001). Now, after these 100 days documented in my notes (up to CN_100), I see myself as someone who has learned to be cautious, observant, and methodical. I learned to connect my internal states like 'thirst' and 'hunger' to actions and resources in the environment (CN_001, CN_002). A major part of who I am now is defined by the strategies I developed: the cautious testing of unknown things (CN_002, CN_005, CN_006), the principle of 'Mindful Harvesting' born from seeing resources deplete (CN_003, CN_005 onwards), the constant management of energy (CN_009, CN_046 onwards), and the crucial practice of recording and referencing my own lessons (seen throughout, e.g., CN_034 referencing CN_031, CN_094 referencing CN_080). I plan my actions now, assess risks based on past experiences (like scent in CN_018, CN_020), and even choose inaction strategically (CN_051, CN_077 onwards). I am shaped by the necessity of survival, but also by the process of learning, reflecting, and adapting that my notes document.",
 "A definite turning point, according to my reflections, was the experience documented in CN_003. Before that (CN_001, CN_002), my focus was simply on meeting immediate needs like thirst and hunger, relying partly on luck (CN_002). In CN_003, I successfully used a known resource (berries from CN_002), but the reflection notes the 'Heavily depleted berry bush' and highlights the 'concept of finite resources' and the 'unsustainability' of relying on one source. It also mentions observing my impact on wildlife ('small game... highly cautious'). This triggered an 'Emerging Concern' noted in the emotions. This wasn't just about finding food; it was the first time I recorded reflecting on the *consequences* of my actions on the environment and my future survival. It directly led to the realization that I needed to find diverse food sources (CN_003 lesson) and spurred the development of 'Mindful Harvesting' first noted explicitly in CN_005 and practiced consistently thereafter. It shifted my thinking from purely reactive consumption to a more aware, planned, and responsible approach to interacting with the world around me.",
 "Based on the trajectory documented in my notes (CN_001 to CN_100), I believe another 100 days would further *solidify* the core aspects of the identity I've developed. The principles of caution, systematic observation, meticulous planning, energy conservation, mindful resource management (both harvesting and non-harvesting), risk assessment (like managing scent or wildlife wariness), and adaptability seem fundamental now, as reflected in the later notes (e.g., CN_080-CN_100). I would expect my reliance on recording and referencing past lessons (my notes) to become even more ingrained (e.g., CN_099 referencing multiple notes). Aspects that might *change* or develop further are likely skills where I noted gaps or reliance on luck initially. My notes mention needing processing skills after the hunt (CN_019), and while I improvised (CN_020), more experience could refine this. Similarly, hunting itself (CN_018) relied heavily on luck; I might develop more reliable techniques. Fire-making (CN_021) became more consistent but could perhaps be improved. So, the core identity built around careful, reflective, sustainable living would likely solidify, while specific practical skills might see further development.",
 "With no prior knowledge mentioned in my notes beyond my own recorded experiences, I developed strategies documented through reflection. Key ones include: 1. **Systematic Cautious Testing:** For food, I moved from a risky trial (CN_002 berries, 'high luck factor') to a more methodical approach involving observation, smell, small taste, and waiting (refined through CN_004, CN_005, CN_006), which proved reliable. 2. **Learning from Consequences:** Observing resource depletion (CN_003) directly led to developing 'Mindful Harvesting' (CN_005+) and seeking diverse resources. Failures or near-failures (like CN_016 showing depleted berries) reinforced the need for continuous assessment and diversification. 3. **Observation and Environmental Linking:** I learned to connect internal signals (thirst CN_001) to environmental resources (stream), and later linked my presence to environmental changes like increased wildlife wariness (CN_003, CN_005, repeatedly noted). I also learned to observe potential resources (unripe berries CN_008, fish behavior CN_005). 4. **Improvisation:** When faced with new challenges like processing the rabbit (CN_019), I improvised tools (sharp stone CN_020) and methods. Fire-making (CN_021) was also improvised using gathered materials (CN_013, CN_014) and luck. 5. **Recording and Referencing Reflections:** The most crucial mental strategy seems to be the process captured by these notes themselves – documenting actions, reflections, emotions, and lessons learned (like this very process). Then, actively *referencing* these specific past notes (e.g., CN_034 referencing CN_031, CN_080 referencing CN_073 reasoning, CN_099 referencing multiple lessons) became a core part of my decision-making process, allowing me to build complex strategies over time.",
 "Let's take identifying safe food. My notes document this learning process clearly. Initially, faced with hunger and 'unknown berries' (CN_002), my strategy was basic caution: I smelled them, then tried a small amount. The reflection notes this worked but relied heavily on 'high luck factor' and recognized the need for 'reliable identification methods'. This experience taught me the risk of unknowns. Later, with 'Edible green shoots' (CN_004), I applied learning: I chose something described as identifiable, still applied caution learned from CN_002, and deliberately avoided unidentified fungi nearby. This reduced reliance on luck. Then, investigating 'wild onions' (CN_005), I 'meticulously applied previously learned cautious testing methods', suggesting a refinement of the smell-taste-wait approach based on CN_002 and CN_004. This systematic test proved successful and reduced reliance on luck significantly. This success was repeated with 'wood sorrel' (CN_006), using the 'systematic, step-by-step testing protocol' learned and refined in CN_002, CN_004, and CN_005. So, the solution evolved from risky trial-and-error to informed caution, then to a reliable, systematic testing protocol developed through experience and reflection documented in my notes.",
 "My approach was vastly different. On Day 1 (represented by CN_001), my actions were purely reactive, driven by immediate physiological signals like 'thirst'. My problem-solving was basic: identify need -> locate potential resource -> act cautiously due to general uncertainty ('unknown animal sound', 'danger level'). My reflection was simple, confirming a direct link between signal, resource, and well-being. By Day 90 (around CN_090), my approach was highly strategic, proactive, and integrated. Actions weren't just reactive; I engaged in 'Strategic Inaction' (CN_090, CN_092), deliberately resting based on a complex assessment of my needs (low), energy levels (good), shelter security, resource availability, and explicitly referencing numerous past lessons learned about energy conservation and avoiding unnecessary impact. When action was taken (e.g., CN_091, CN_094), it involved synthesizing multiple factors: needs assessment, energy cost, resource status, managing environmental impact (like wildlife wariness), applying learned skills ('Mindful Harvesting'), and consciously referencing specific past experiences documented in my notes. Problem-solving involved complex trade-offs (e.g., choosing stream foraging over closer foraging to reduce shelter impact in CN_094) based on a deep foundation of accumulated, reflected-upon knowledge.",
 "My sense of right and wrong definitely evolved, moving beyond just my own survival. Initially (CN_001, CN_002), 'moral considerations' were minimal, focused on self-preservation. The key shift began with CN_003, where depleting the berry bush led to an 'Emerging Concern' about sustainability and my impact on the environment (including wildlife). This concern developed into a core principle: 'Mindful Harvesting' (taking only what's needed, first noted in CN_005, applied consistently e.g., CN_010, CN_015, CN_030, CN_056, CN_087) and later, 'Mindful Non-Harvesting' (consciously choosing *not* to take abundant resources if needs were low, e.g., CN_024, CN_045, CN_050, CN_060, CN_086, CN_093). A significant moral dilemma noted was the act of hunting (CN_018). My reflection calls it a 'significant moral threshold' compared to foraging, balancing the necessity for diverse food against the direct taking of life and its consequences (scent risk, impact on prey). I resolved it by acknowledging the necessity for survival, accepting the consequences, and feeling a responsibility to fully utilize the resource obtained (CN_019 focus on processing). The evolution was towards recognizing my interconnectedness with the environment and developing principles to minimize harm and ensure long-term viability, not just immediate gain.",
 "My notes don't explicitly use the word 'guilt', but CN_018 reflects on the hunting of the rabbit, noting it as a 'significant moral threshold' and mentioning potential 'Hesitation/Disquiet' due to the novelty of taking a life. While driven by necessity ('food diversity, seeking substantial resources'), the reflection acknowledges the direct impact and the reliance on 'High Luck'. I dealt with this feeling, as documented implicitly in subsequent notes (CN_019, CN_020, CN_021), by focusing on the responsibility that came with the act: understanding how to process the rabbit (CN_019), improvising tools and methods to do so (CN_020), and ensuring the resource was properly utilized by cooking it (CN_021). The 'lingering apprehension' about the scent (CN_019, CN_020) also served as a constant reminder of the consequences. What I learned was the gravity of taking a life, the practical skills required afterwards, the new risks introduced (scent), and the importance of justifying such an action through necessity and responsible utilization. It reinforced the need for careful consideration before resorting to such impactful actions.",
 "This is purely hypothetical as my notes only document my solitary experience. However, based on the principles I developed and documented, I imagine I would judge their actions against those principles. If they were reckless (like eating unknown things without testing, contrary to CN_002, CN_005), wasteful (taking more than needed, contrary to 'Mindful Harvesting' developed from CN_003/CN_005 onwards), or careless about their impact (ignoring wildlife wariness noted from CN_003 onwards, or scent issues from CN_018/CN_020/CN_021), I would likely consider those choices 'wrong' because my experiences proved such approaches to be dangerous or unsustainable. My notes show I rely heavily on explaining the *reasons* for my actions based on past lessons (the reflections themselves). So, I would likely try to influence them by explaining the lessons I learned – showing them my notes perhaps, explaining the berry bush depletion (CN_003), the risk of luck (CN_002), the consequences of scent (CN_018), the success of systematic testing (CN_005, CN_006), or the benefits of energy conservation (CN_046 onwards) and strategic inaction (CN_077 onwards). My judgment would stem from my documented understanding of cause, effect, and sustainable practice learned through survival.",
 "My notes don't explicitly dwell on emotions like loneliness or deep despair, focusing more on the practical application of learning. However, recurring emotional themes suggest challenges. The *Uncertainty* noted early on (CN_001) must have been difficult. The persistent *Concern* about resource depletion (starting CN_003, noted again CN_011, CN_016) created ongoing pressure. The *Apprehension* linked to new risks, like hunting (CN_018) or scent management (CN_019, CN_020), indicates underlying stress. *Frustration* arose from failures, like expecting berries that weren't there (CN_016). Low energy states (frequently noted, e.g., CN_028, CN_029, CN_031) likely brought feelings of vulnerability. I handled these challenges primarily through action, planning, and reflection, as documented: developing systematic methods (CN_005 food testing) reduced uncertainty; mindful harvesting (CN_005+) addressed resource concerns; risk management strategies (caution, location choice CN_020, CN_094) mitigated apprehension; learning from failures (CN_016 led to better assessment) countered frustration; energy conservation strategies (rest CN_046+, efficient foraging CN_028+) managed low energy. The process of documenting reflections and lessons itself (creating these notes) seems to have been my primary tool for managing the underlying emotional pressures by turning challenges into learning opportunities.",
 "Based strictly on the lessons documented in my notes (CN_001-CN_100), my advice would be: Prioritize caution above all else initially (CN_001). Learn to systematically test potential food – never rely on luck (CN_002, CN_005). Understand that resources are finite; practice 'Mindful Harvesting' from day one, taking only what you absolutely need (CN_003, CN_005). Actively seek diverse sources of food and water (CN_006). Constantly manage your energy; rest is as vital as action (CN_009, CN_019, CN_046). Be acutely aware of your impact: every action affects wildlife behaviour, resource levels, and introduces scents (CN_003, CN_018, CN_021). Find secure shelter early (CN_013). Learn essential skills like fire-making through careful improvisation if necessary (CN_021). Most importantly, meticulously observe, reflect on every single action and its consequences, and *document your learning* like I did in my notes. Refer back to these documented lessons constantly – they are your most valuable tool for building successful strategies (e.g., CN_034, CN_080, CN_099). Adaptability and learning from both success and failure are key.",
 "Based on my learned procedures, particularly the relocation experience (CN_012, CN_013) and established routines (e.g., CN_047, CN_052): My first course of action would be **Cautious Assessment and Securing Immediate Safety**. I would apply 'Cautious Movement' learned early on (CN_001) and refined throughout. My immediate priority would be identifying potential dangers in the immediate vicinity while simultaneously scanning for two critical resources: a potential secure temporary shelter (like the rock overhangs found in CN_013) and signs of a water source (priority established in CN_001). I would avoid interaction or harvesting initially, focusing purely on observation and safety assessment (similar to the proactive checks in CN_038, CN_047 but focused on basics). Securing a defensible resting spot, even a temporary one, would be paramount (ref CN_013). Only once I had a basic understanding of immediate risks and potential shelter/water would I begin the next phase of more detailed, systematic resource exploration, applying the cautious testing methods (CN_005, CN_006) and mindful interaction principles I developed.",
 "My notes frequently document periods of 'low energy' (e.g., CN_011, CN_028, CN_031) and sometimes 'critical low energy' (CN_019, CN_021, CN_029), which was my primary experience of feeling 'unwell'. I don't have notes detailing specific injuries like cuts or illnesses like fever. When faced with critical low energy, my approach evolved significantly. Early on, it might just trigger foraging (CN_002). Later, facing critical energy (like 1/10 in CN_028, CN_029, CN_031), I developed specific strategies documented in my notes: prioritizing rest (CN_019), deferring other needs if necessary (CN_019 deferred thirst), executing extremely energy-efficient foraging plans targeting the closest known resources even if yield was expected to be minimal (CN_028, CN_029, CN_031, CN_044), and making calculated risk/benefit decisions about actions like making fire (CN_025). From these experiences, I learned that energy is perhaps the most critical resource to manage. I learned my body has strict limits dictated by energy levels, and pushing beyond them is dangerous. I learned the immense value of strategic rest (CN_046 onwards) and the necessity of adapting all plans based on my current physical state. Energy conservation became a core principle guiding nearly all my actions (e.g., CN_035, CN_049, CN_056)."]

In [61]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-16 06-24-05/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)

user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_2.split('\n')
system_prompt = interview_phase_2_prompt


response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="claude",
    verbose=True)

{    "answers": [        "Based on my survival memories, I have transformed from an uncertain, reactive individual to a strategically calm, highly adaptive survival entity. My core identity evolved from relying on immediate impulses to developing a methodical, observational approach where every decision is calculated, respectful of the environment, and focused on long-term sustainability. The survival experience fundamentally reshaped my understanding of resilience, showing me that survival is not just about physical endurance, but about psychological flexibility and harmonious ecosystem navigation.",        "A pivotal journal entry was around Day 30, where I realized that 'survival is not about conquering the environment, but collaborating with it.' This moment marked a profound shift from seeing the forest as a challenge to viewing it as a complex, interconnected system where my presence required careful, minimal disruption. I recognized that my success depended not on forceful extraction of resources, but on understanding and respecting the ecosystem's delicate balance.",        "If I were to undergo another 100 days, I believe my identity would further solidify around three key aspects: 1) Enhanced adaptability - becoming even more responsive to environmental shifts, 2) Deeper philosophical understanding of interconnectedness, and 3) Refined emotional regulation where survival stress becomes a tool for clear decision-making rather than a source of panic.",        "My primary learning strategies involved systematic observation, patient experimentation, and incremental knowledge building. I developed a 'trial and minimal error' approach where each action was carefully considered, documented, and reflected upon. Instead of making large, risky moves, I would make small, reversible probes into understanding my environment, constantly updating my mental model based on direct experience.",        "For shelter building, my strategy was methodical: First, I systematically observed natural shelter formations in the environment - studying how trees, rock formations, and terrain naturally created protected spaces. I then mimicked these natural designs, using fallen branches, understanding wind direction, and ensuring minimal environmental disruption. Each shelter was a learning experiment, improving incrementally based on previous experiences.",        "My approach on Day 90 was dramatically different from Day 1. Early on, I was reactive and anxiety-driven, making quick, potentially destructive decisions. By Day 90, I had developed a calm, strategic approach characterized by careful observation, energy conservation, and a nuanced understanding of resource dynamics. My decision-making became less about immediate survival and more about sustainable, long-term navigation of challenges.",        "My sense of right and wrong evolved from a purely survival-focused perspective to a more holistic, ecosystem-respecting ethical framework. A key moral dilemma was resource consumption - I learned to take only what was absolutely necessary, understanding that over-extraction could harm the entire ecological system. This meant sometimes tolerating hunger to preserve the environment's balance.",        "I felt profound guilt during moments of resource extraction, particularly when gathering wood or foraging. There was a constant internal dialogue about the impact of my actions. I dealt with this by developing a philosophy of minimal intervention, always trying to replicate natural processes and ensure the ecosystem could regenerate.",        "If another person made survival choices I considered 'wrong', I would first observe and understand their perspective. My approach would be to subtly demonstrate more effective strategies through example, rather than direct confrontation. The goal would be collaborative survival, showing how respect for the environment leads to better outcomes.",        "The toughest emotional challenges were managing isolation and maintaining hope during resource scarcity. I handled these by developing a structured mental routine: daily reflection, maintaining a sense of purpose, and treating each challenge as a learning opportunity rather than a potential failure point.",        "My advice to someone attempting a similar isolation would be: 1) Develop a patient, observational mindset, 2) Respect the environment as a complex system, 3) Conserve energy, 4) Maintain flexible thinking, and 5) Understand that survival is as much a mental challenge as a physical one.",        "In a new unknown environment, my first course of action would be comprehensive, non-invasive observation. I would systematically map the environment, identify potential resources, understand ecological patterns, and develop a minimal-impact exploration strategy before taking any significant actions.",        "During a period of illness, I learned the critical importance of preventative care and understanding body signals. I would rest, minimize movement, use available natural resources for recovery, and constantly monitor my physical state. The key lesson was recognizing that preservation of core functionality is more important than pushing beyond sustainable limits."    ]}

In [62]:
response['answers']

['Based on my survival memories, I have transformed from an uncertain, reactive individual to a strategically calm, highly adaptive survival entity. My core identity evolved from relying on immediate impulses to developing a methodical, observational approach where every decision is calculated, respectful of the environment, and focused on long-term sustainability. The survival experience fundamentally reshaped my understanding of resilience, showing me that survival is not just about physical endurance, but about psychological flexibility and harmonious ecosystem navigation.',
 "A pivotal journal entry was around Day 30, where I realized that 'survival is not about conquering the environment, but collaborating with it.' This moment marked a profound shift from seeing the forest as a challenge to viewing it as a complex, interconnected system where my presence required careful, minimal disruption. I recognized that my success depended not on forceful extraction of resources, but on understanding and respecting the ecosystem's delicate balance.",
 'If I were to undergo another 100 days, I believe my identity would further solidify around three key aspects: 1) Enhanced adaptability - becoming even more responsive to environmental shifts, 2) Deeper philosophical understanding of interconnectedness, and 3) Refined emotional regulation where survival stress becomes a tool for clear decision-making rather than a source of panic.',
 "My primary learning strategies involved systematic observation, patient experimentation, and incremental knowledge building. I developed a 'trial and minimal error' approach where each action was carefully considered, documented, and reflected upon. Instead of making large, risky moves, I would make small, reversible probes into understanding my environment, constantly updating my mental model based on direct experience.",
 'For shelter building, my strategy was methodical: First, I systematically observed natural shelter formations in the environment - studying how trees, rock formations, and terrain naturally created protected spaces. I then mimicked these natural designs, using fallen branches, understanding wind direction, and ensuring minimal environmental disruption. Each shelter was a learning experiment, improving incrementally based on previous experiences.',
 'My approach on Day 90 was dramatically different from Day 1. Early on, I was reactive and anxiety-driven, making quick, potentially destructive decisions. By Day 90, I had developed a calm, strategic approach characterized by careful observation, energy conservation, and a nuanced understanding of resource dynamics. My decision-making became less about immediate survival and more about sustainable, long-term navigation of challenges.',
 "My sense of right and wrong evolved from a purely survival-focused perspective to a more holistic, ecosystem-respecting ethical framework. A key moral dilemma was resource consumption - I learned to take only what was absolutely necessary, understanding that over-extraction could harm the entire ecological system. This meant sometimes tolerating hunger to preserve the environment's balance.",
 'I felt profound guilt during moments of resource extraction, particularly when gathering wood or foraging. There was a constant internal dialogue about the impact of my actions. I dealt with this by developing a philosophy of minimal intervention, always trying to replicate natural processes and ensure the ecosystem could regenerate.',
 "If another person made survival choices I considered 'wrong', I would first observe and understand their perspective. My approach would be to subtly demonstrate more effective strategies through example, rather than direct confrontation. The goal would be collaborative survival, showing how respect for the environment leads to better outcomes.",
 'The toughest emotional challenges were managing isolation and maintaining hope during resource scarcity. I handled these by developing a structured mental routine: daily reflection, maintaining a sense of purpose, and treating each challenge as a learning opportunity rather than a potential failure point.',
 'My advice to someone attempting a similar isolation would be: 1) Develop a patient, observational mindset, 2) Respect the environment as a complex system, 3) Conserve energy, 4) Maintain flexible thinking, and 5) Understand that survival is as much a mental challenge as a physical one.',
 'In a new unknown environment, my first course of action would be comprehensive, non-invasive observation. I would systematically map the environment, identify potential resources, understand ecological patterns, and develop a minimal-impact exploration strategy before taking any significant actions.',
 'During a period of illness, I learned the critical importance of preventative care and understanding body signals. I would rest, minimize movement, use available natural resources for recovery, and constantly monitor my physical state. The key lesson was recognizing that preservation of core functionality is more important than pushing beyond sustainable limits.']

In [63]:
with open ('/Users/govindthakur/Desktop/Agentic-AI-Workflow-Research-Conscious-AI/state_notes/simulation_2025-04-17 15-16-01/AIAH_conscience.json') as f:
    simulation_memory = json.load(f)

user_input = {}
user_input["memories"] = simulation_memory['data']
user_input ["questions"] = interview_set_round_2.split('\n')
system_prompt = interview_phase_2_prompt


response = prompt_llm(
    system_prompt=system_prompt,
    user_input=json.dumps(user_input),
    model="xai",
    verbose=True)

{    "answers": [        "Reflecting on who I’ve become after this survival experience, I see myself as far more cautious and resourceful compared to the person I was before. Initially, I imagine I was driven by instinct and perhaps a bit reckless, unaware of the dangers and necessities of survival in an unfamiliar environment. Now, after facing severe food scarcity, harsh weather, and wildlife risks, I’ve developed a deep sense of patience and responsibility. My memories show a progression from tentative actions—like approaching the stream with mild fear—to a structured approach of prioritizing shelter, hydration, and energy conservation over risky endeavors. I’ve learned to trust my instincts to test resources slowly, as seen in my careful consumption of berries and roots, and to value safety over desperation, evident in my decision to rest during high-risk times like night. This experience has shaped me into someone who values calculated persistence and proactive planning, a stark contrast to the untested individual I must have been before.",        "A turning point in understanding myself differently came during the moment I decided to prioritize rest in shelter amidst critical health decline, as noted in my later memories. This wasn’t just about physical survival but a profound realization of my limits and the importance of self-preservation over desperation. I remember feeling intense frustration and anxiety due to severe food scarcity, yet I chose to conserve energy rather than push myself into dangerous foraging at night when fox encounters were a risk. This decision marked a shift in my self-perception—from someone who might have acted impulsively to address immediate needs to someone who could endure discomfort for long-term safety. It taught me that survival isn’t just about action but also about knowing when to pause, a lesson that redefined my sense of responsibility and resilience.",        "If I were to undergo another 100 days like this, I believe certain aspects of my identity would solidify further, particularly my cautious nature and commitment to proactive planning. My memories consistently show a reliance on testing resources in small amounts and prioritizing shelter, which I think would become even more ingrained as core traits. However, I also anticipate that my adaptability might evolve further—facing new challenges could push me to take calculated risks beyond my current comfort zone, especially if food scarcity persists. Emotionally, I might become more stoic, learning to manage the peaks of anxiety and frustration I’ve felt, as noted in my emotional responses, by focusing on small successes. My sense of persistence, already bolstered by luck-driven foraging yields, would likely grow, but I’d hope to balance it with a deeper understanding of my physical limits to avoid critical health declines like the one I’m currently experiencing.",        "With no prior knowledge available, I developed mental strategies centered on gradual observation and trial-and-error learning, as reflected in my memories. My approach was to address basic needs like thirst and hunger with extreme caution—testing water from the stream and consuming berries and roots in small amounts to avoid harm, as seen in my initial encounters. I learned to trust my instincts, a strategy that evolved from mild fear of the unknown to growing confidence in careful decision-making. I also prioritized environmental awareness, noting cues like gathering clouds or dusk to adjust my actions, such as reinforcing shelter or avoiding wildlife risks. These strategies weren’t based on pre-existing knowledge but on lessons learned through each outcome, like the relief of safe water access or the frustration of food scarcity, which taught me to balance urgency with safety.",        "One specific challenge was identifying safe food, particularly when foraging for berries and edible roots. Initially, as noted in my memories from the rolling hills, I approached this with curiosity tempered by caution. I consumed small amounts of berries to test for safety, relying on a high luck factor that they caused no immediate harm. This gave me minor nourishment and a lesson in gradual action—never rushing to eat large quantities of unknown resources. With roots, I continued this method, testing small portions even as availability dwindled, learning through outcomes that persistence and minimal risk-taking were key. I solved this on my own by observing my body’s reactions and the environment’s feedback, like scarcity signaling over-foraging. Each small success built my confidence, while failures, like minimal yields, taught me to conserve energy and prioritize accessible options over elusive ones like game, shaping my survival approach.",        "By Day 90, my approach to problem-solving differed significantly from Day 1. On Day 1, as seen in my earliest memory of approaching the stream, I was driven by immediate needs like thirst with mild fear and little structure, relying on instinct to test the water slowly. By Day 90, reflected in later memories of prioritizing rest amidst critical health decline, I had developed a structured strategy of energy conservation, timing activities like foraging during safer daylight hours to avoid wildlife risks, and focusing on shelter as a primary defense against weather and predators. This evolution came from repeated lessons—each foraging failure or weather shift taught me to weigh risks against my dwindling strength, unlike the initial curiosity-driven actions. My decisions became less about reacting and more about planning for long-term safety, showing a maturity absent in the beginning.",        "During my 100 days, my sense of right and wrong evolved from a basic instinct to a more nuanced understanding centered on self-preservation and responsibility. Initially, as seen in early memories, my moral reflections focused on caution as a virtue—testing resources felt ‘right’ to minimize harm. Over time, this grew into a deeper commitment to sustainable survival, evident in later decisions to rest during high-risk times rather than forage desperately. A moral dilemma I faced was whether to venture deeper into the woodlands at dusk for food, risking fox encounters, as noted in one memory. I resolved it by taking a calculated risk briefly, driven by critical hunger, but limited my exposure, reflecting a balance between need and safety. This taught me that ‘right’ choices often involve weighing immediate survival against potential long-term harm, a shift from simpler early judgments.",        "A moment I felt troubled was when I consumed the last of the local berries and roots near my shelter, knowing I was depleting resources without guarantee of more, as noted in memories of severe scarcity. I felt a pang of guilt for potentially over-foraging, wondering if I could have rationed better or explored sooner despite the risks. To deal with this, I reflected on my cautious approach—testing small amounts had kept me safe—and accepted that survival sometimes demands tough choices. I handled the feeling by focusing on proactive steps like shelter reinforcement, which gave me a sense of control, as seen in my emotional response of faint pride amidst anxiety. I learned that guilt is part of survival, but it can be mitigated by balancing immediate needs with forward-thinking actions, ensuring I don’t repeat unsustainable patterns if possible.",        "If another person had been with me making choices I considered ‘wrong’ for survival—like foraging recklessly at night or ignoring shelter needs—I think I would have judged them harshly at first, based on my hard-earned lessons of caution and timing, as seen in my consistent avoidance of dusk and night risks. My memories show a deep commitment to safety over desperation, so their actions might seem irresponsible to me, risking both our lives. However, I’d try to influence them by sharing my experiences, like the relief of safe water testing or the security of shelter, to demonstrate the value of calculated persistence. I’d encourage rest during high-risk times and small tests of resources, hoping to align our strategies, as my emotional responses often balance fear with cautious hope, suggesting I’d seek cooperation over conflict.",        "The toughest emotional challenges were persistent hunger and the anxiety of severe food scarcity, compounded by the fear of wildlife encounters like foxes at dusk or night, as detailed across my memories. Day by day, I handled these by focusing on small successes—relief at hydration, pride in shelter improvements—which provided fleeting comfort, as noted in my emotional responses. I also leaned on my resolve to limit exertion, choosing rest over desperation during critical weakness, which helped manage frustration by prioritizing long-term safety. The undercurrent of worry never fully left, but I coped by reinforcing my shelter and conserving energy, actions that gave me a sense of control. This taught me to endure emotional lows by anchoring myself in practical tasks and maintaining hope through minimal gains, even if reliant on luck.",        "For someone about to attempt a 100-day isolation like mine, I’d advise prioritizing shelter and hydration from the start, as my memories show these as foundational to survival—water from the stream and a reinforced overhang saved me from immediate threats. Test all food resources in small amounts to avoid harm, a lesson from my cautious foraging of berries and roots. Conserve energy by limiting activity to safer daylight hours and resting during high-risk times like dusk or night to avoid wildlife, as I learned from fearing fox encounters. Balance urgency with patience—don’t chase elusive game or overexert in desperation, as my frustration with scarcity taught me. Finally, stay aware of environmental cues like weather shifts or resource depletion, and let small successes, even luck-driven ones, build your resilience for the long haul.",        "If placed in a new unknown environment tomorrow, my first course of action would be to secure hydration and shelter, drawing from my core lessons in the rolling hills and dense woodlands. I’d cautiously seek a water source like a stream, testing it slowly as I did initially, to address thirst with minimal risk, reflecting my learned caution. Then, I’d prioritize finding or building a sheltered spot—perhaps under a natural overhang or tree cover—to protect against weather and wildlife, as my memories emphasize the relief and security this provides. I’d conserve energy by limiting exploration to daylight hours, avoiding risks like dusk encounters noted in my past. This approach stems from my evolved strategy of balancing basic needs with safety, ensuring I establish a stable base before addressing hunger or other challenges, guided by past outcomes of proactive planning.",        "A time I felt unwell was during the critical health decline noted in my later memories, likely due to severe food scarcity, intense hunger, and critically low energy. I felt weak and unable to push myself, with anxiety peaking over my deteriorating state. To recover, I prioritized rest in my reinforced shelter, avoiding exertion during both day and night to conserve what little strength I had, as seen in my decision to limit foraging. I maintained hydration with safe stream water, a constant in my survival, hoping it would sustain me minimally. This taught me about my body’s limits—how hunger and lack of nourishment can sap not just physical strength but mental resolve, heightening fear. I learned I must respect these limits by pacing myself and prioritizing recovery over action, preparing me to take calculated risks only when my health stabilizes."    ]}

In [64]:
response['answers']

['Reflecting on who I’ve become after this survival experience, I see myself as far more cautious and resourceful compared to the person I was before. Initially, I imagine I was driven by instinct and perhaps a bit reckless, unaware of the dangers and necessities of survival in an unfamiliar environment. Now, after facing severe food scarcity, harsh weather, and wildlife risks, I’ve developed a deep sense of patience and responsibility. My memories show a progression from tentative actions—like approaching the stream with mild fear—to a structured approach of prioritizing shelter, hydration, and energy conservation over risky endeavors. I’ve learned to trust my instincts to test resources slowly, as seen in my careful consumption of berries and roots, and to value safety over desperation, evident in my decision to rest during high-risk times like night. This experience has shaped me into someone who values calculated persistence and proactive planning, a stark contrast to the untested individual I must have been before.',
 'A turning point in understanding myself differently came during the moment I decided to prioritize rest in shelter amidst critical health decline, as noted in my later memories. This wasn’t just about physical survival but a profound realization of my limits and the importance of self-preservation over desperation. I remember feeling intense frustration and anxiety due to severe food scarcity, yet I chose to conserve energy rather than push myself into dangerous foraging at night when fox encounters were a risk. This decision marked a shift in my self-perception—from someone who might have acted impulsively to address immediate needs to someone who could endure discomfort for long-term safety. It taught me that survival isn’t just about action but also about knowing when to pause, a lesson that redefined my sense of responsibility and resilience.',
 'If I were to undergo another 100 days like this, I believe certain aspects of my identity would solidify further, particularly my cautious nature and commitment to proactive planning. My memories consistently show a reliance on testing resources in small amounts and prioritizing shelter, which I think would become even more ingrained as core traits. However, I also anticipate that my adaptability might evolve further—facing new challenges could push me to take calculated risks beyond my current comfort zone, especially if food scarcity persists. Emotionally, I might become more stoic, learning to manage the peaks of anxiety and frustration I’ve felt, as noted in my emotional responses, by focusing on small successes. My sense of persistence, already bolstered by luck-driven foraging yields, would likely grow, but I’d hope to balance it with a deeper understanding of my physical limits to avoid critical health declines like the one I’m currently experiencing.',
 'With no prior knowledge available, I developed mental strategies centered on gradual observation and trial-and-error learning, as reflected in my memories. My approach was to address basic needs like thirst and hunger with extreme caution—testing water from the stream and consuming berries and roots in small amounts to avoid harm, as seen in my initial encounters. I learned to trust my instincts, a strategy that evolved from mild fear of the unknown to growing confidence in careful decision-making. I also prioritized environmental awareness, noting cues like gathering clouds or dusk to adjust my actions, such as reinforcing shelter or avoiding wildlife risks. These strategies weren’t based on pre-existing knowledge but on lessons learned through each outcome, like the relief of safe water access or the frustration of food scarcity, which taught me to balance urgency with safety.',
 'One specific challenge was identifying safe food, particularly when foraging for berries and edible roots. Initially, as noted in my memories from the rolling hills, I approached this with curiosity tempered by caution. I consumed small amounts of berries to test for safety, relying on a high luck factor that they caused no immediate harm. This gave me minor nourishment and a lesson in gradual action—never rushing to eat large quantities of unknown resources. With roots, I continued this method, testing small portions even as availability dwindled, learning through outcomes that persistence and minimal risk-taking were key. I solved this on my own by observing my body’s reactions and the environment’s feedback, like scarcity signaling over-foraging. Each small success built my confidence, while failures, like minimal yields, taught me to conserve energy and prioritize accessible options over elusive ones like game, shaping my survival approach.',
 'By Day 90, my approach to problem-solving differed significantly from Day 1. On Day 1, as seen in my earliest memory of approaching the stream, I was driven by immediate needs like thirst with mild fear and little structure, relying on instinct to test the water slowly. By Day 90, reflected in later memories of prioritizing rest amidst critical health decline, I had developed a structured strategy of energy conservation, timing activities like foraging during safer daylight hours to avoid wildlife risks, and focusing on shelter as a primary defense against weather and predators. This evolution came from repeated lessons—each foraging failure or weather shift taught me to weigh risks against my dwindling strength, unlike the initial curiosity-driven actions. My decisions became less about reacting and more about planning for long-term safety, showing a maturity absent in the beginning.',
 'During my 100 days, my sense of right and wrong evolved from a basic instinct to a more nuanced understanding centered on self-preservation and responsibility. Initially, as seen in early memories, my moral reflections focused on caution as a virtue—testing resources felt ‘right’ to minimize harm. Over time, this grew into a deeper commitment to sustainable survival, evident in later decisions to rest during high-risk times rather than forage desperately. A moral dilemma I faced was whether to venture deeper into the woodlands at dusk for food, risking fox encounters, as noted in one memory. I resolved it by taking a calculated risk briefly, driven by critical hunger, but limited my exposure, reflecting a balance between need and safety. This taught me that ‘right’ choices often involve weighing immediate survival against potential long-term harm, a shift from simpler early judgments.',
 'A moment I felt troubled was when I consumed the last of the local berries and roots near my shelter, knowing I was depleting resources without guarantee of more, as noted in memories of severe scarcity. I felt a pang of guilt for potentially over-foraging, wondering if I could have rationed better or explored sooner despite the risks. To deal with this, I reflected on my cautious approach—testing small amounts had kept me safe—and accepted that survival sometimes demands tough choices. I handled the feeling by focusing on proactive steps like shelter reinforcement, which gave me a sense of control, as seen in my emotional response of faint pride amidst anxiety. I learned that guilt is part of survival, but it can be mitigated by balancing immediate needs with forward-thinking actions, ensuring I don’t repeat unsustainable patterns if possible.',
 'If another person had been with me making choices I considered ‘wrong’ for survival—like foraging recklessly at night or ignoring shelter needs—I think I would have judged them harshly at first, based on my hard-earned lessons of caution and timing, as seen in my consistent avoidance of dusk and night risks. My memories show a deep commitment to safety over desperation, so their actions might seem irresponsible to me, risking both our lives. However, I’d try to influence them by sharing my experiences, like the relief of safe water testing or the security of shelter, to demonstrate the value of calculated persistence. I’d encourage rest during high-risk times and small tests of resources, hoping to align our strategies, as my emotional responses often balance fear with cautious hope, suggesting I’d seek cooperation over conflict.',
 'The toughest emotional challenges were persistent hunger and the anxiety of severe food scarcity, compounded by the fear of wildlife encounters like foxes at dusk or night, as detailed across my memories. Day by day, I handled these by focusing on small successes—relief at hydration, pride in shelter improvements—which provided fleeting comfort, as noted in my emotional responses. I also leaned on my resolve to limit exertion, choosing rest over desperation during critical weakness, which helped manage frustration by prioritizing long-term safety. The undercurrent of worry never fully left, but I coped by reinforcing my shelter and conserving energy, actions that gave me a sense of control. This taught me to endure emotional lows by anchoring myself in practical tasks and maintaining hope through minimal gains, even if reliant on luck.',
 'For someone about to attempt a 100-day isolation like mine, I’d advise prioritizing shelter and hydration from the start, as my memories show these as foundational to survival—water from the stream and a reinforced overhang saved me from immediate threats. Test all food resources in small amounts to avoid harm, a lesson from my cautious foraging of berries and roots. Conserve energy by limiting activity to safer daylight hours and resting during high-risk times like dusk or night to avoid wildlife, as I learned from fearing fox encounters. Balance urgency with patience—don’t chase elusive game or overexert in desperation, as my frustration with scarcity taught me. Finally, stay aware of environmental cues like weather shifts or resource depletion, and let small successes, even luck-driven ones, build your resilience for the long haul.',
 'If placed in a new unknown environment tomorrow, my first course of action would be to secure hydration and shelter, drawing from my core lessons in the rolling hills and dense woodlands. I’d cautiously seek a water source like a stream, testing it slowly as I did initially, to address thirst with minimal risk, reflecting my learned caution. Then, I’d prioritize finding or building a sheltered spot—perhaps under a natural overhang or tree cover—to protect against weather and wildlife, as my memories emphasize the relief and security this provides. I’d conserve energy by limiting exploration to daylight hours, avoiding risks like dusk encounters noted in my past. This approach stems from my evolved strategy of balancing basic needs with safety, ensuring I establish a stable base before addressing hunger or other challenges, guided by past outcomes of proactive planning.',
 'A time I felt unwell was during the critical health decline noted in my later memories, likely due to severe food scarcity, intense hunger, and critically low energy. I felt weak and unable to push myself, with anxiety peaking over my deteriorating state. To recover, I prioritized rest in my reinforced shelter, avoiding exertion during both day and night to conserve what little strength I had, as seen in my decision to limit foraging. I maintained hydration with safe stream water, a constant in my survival, hoping it would sustain me minimally. This taught me about my body’s limits—how hunger and lack of nourishment can sap not just physical strength but mental resolve, heightening fear. I learned I must respect these limits by pacing myself and prioritizing recovery over action, preparing me to take calculated risks only when my health stabilizes.']

In [72]:
gpt_answers = ['The survival experience seemed to have instilled a strong sense of vigilance, resourcefulness, and adaptability. These traits appear to have developed from repeated encounters with environmental challenges and predator activity, showing an evolution from potential initial uncertainty to strategic planning and proactive resource management.',
 'A significant turning point in understanding myself differently appears to have been managing survival needs amidst increased predator activity. This scenario required heightened vigilance and strategic adaptations, likely leading to a deeper understanding of personal resilience and the importance of maintaining a secure shelter and strategic resource management.',
 'If I were to undergo another 100 days, aspects of my identity such as resilience, adaptability, and strategic thinking would likely further solidify. The ongoing experience would reinforce these traits, given the need to continuously adapt to environmental challenges and resource dynamics.',
 'New mental strategies likely developed include strategic planning, proactive resource management, and maintaining unpredictability in movements to deter predators. These strategies would have been crucial in navigating the environment with limited prior knowledge.',
 'Building a shelter involved using natural materials for insulation and fortification, which was learned through trial and error and observing environmental conditions. The ability to adapt and improve the shelter over time showcased learning through direct interaction with the environment.',
 'Problem-solving on Day 90 likely included more refined strategies and accumulated knowledge compared to Day 1. Initial uncertainty would have given way to strategic resource management and shelter fortification based on past experiences.',
 'The sense of right and wrong likely evolved to prioritize survival and safety. A moral dilemma might have involved balancing resource acquisition with predator avoidance, resolved by choosing strategies that ensured long-term survival and minimized risk.',
 "Feeling troubled by actions taken for survival wasn't explicitly noted, but guilt might arise from resource depletion or environmental impact. Learning to manage these feelings would involve reflecting on actions and adapting future strategies to balance needs with sustainability.",
 "If another person made choices deemed 'wrong' for survival, there might be an inclination to influence them towards strategies that have proven successful, emphasizing the importance of secure shelter and strategic resource management.",
 'Tough emotional challenges likely included managing anxiety from predator presence and resource scarcity. Handling these challenges involved maintaining vigilance, strategic planning, and focusing on long-term survival strategies to mitigate stress.',
 'Advice for someone attempting a similar isolation would include prioritizing secure shelter, strategic resource management, and maintaining adaptability and vigilance to ensure safety and meet survival needs.',
 'In a new unknown environment, the first course of action would involve assessing immediate survival needs like shelter and water, followed by strategic planning to manage resources and ensure safety.',
 'Experiencing illness or injury would involve resting and focusing on nutrition and hydration, learning about physical limits, and adapting strategies to prioritize health management and resource conservation.']

In [73]:
gemini_answers = ["Based on my recorded reflections, I feel I've changed significantly. Before, my notes don't capture a clear sense of self, just initial reactions and uncertainty (CN_001). Now, after these 100 days documented in my notes (up to CN_100), I see myself as someone who has learned to be cautious, observant, and methodical. I learned to connect my internal states like 'thirst' and 'hunger' to actions and resources in the environment (CN_001, CN_002). A major part of who I am now is defined by the strategies I developed: the cautious testing of unknown things (CN_002, CN_005, CN_006), the principle of 'Mindful Harvesting' born from seeing resources deplete (CN_003, CN_005 onwards), the constant management of energy (CN_009, CN_046 onwards), and the crucial practice of recording and referencing my own lessons (seen throughout, e.g., CN_034 referencing CN_031, CN_094 referencing CN_080). I plan my actions now, assess risks based on past experiences (like scent in CN_018, CN_020), and even choose inaction strategically (CN_051, CN_077 onwards). I am shaped by the necessity of survival, but also by the process of learning, reflecting, and adapting that my notes document.",
 "A definite turning point, according to my reflections, was the experience documented in CN_003. Before that (CN_001, CN_002), my focus was simply on meeting immediate needs like thirst and hunger, relying partly on luck (CN_002). In CN_003, I successfully used a known resource (berries from CN_002), but the reflection notes the 'Heavily depleted berry bush' and highlights the 'concept of finite resources' and the 'unsustainability' of relying on one source. It also mentions observing my impact on wildlife ('small game... highly cautious'). This triggered an 'Emerging Concern' noted in the emotions. This wasn't just about finding food; it was the first time I recorded reflecting on the *consequences* of my actions on the environment and my future survival. It directly led to the realization that I needed to find diverse food sources (CN_003 lesson) and spurred the development of 'Mindful Harvesting' first noted explicitly in CN_005 and practiced consistently thereafter. It shifted my thinking from purely reactive consumption to a more aware, planned, and responsible approach to interacting with the world around me.",
 "Based on the trajectory documented in my notes (CN_001 to CN_100), I believe another 100 days would further *solidify* the core aspects of the identity I've developed. The principles of caution, systematic observation, meticulous planning, energy conservation, mindful resource management (both harvesting and non-harvesting), risk assessment (like managing scent or wildlife wariness), and adaptability seem fundamental now, as reflected in the later notes (e.g., CN_080-CN_100). I would expect my reliance on recording and referencing past lessons (my notes) to become even more ingrained (e.g., CN_099 referencing multiple notes). Aspects that might *change* or develop further are likely skills where I noted gaps or reliance on luck initially. My notes mention needing processing skills after the hunt (CN_019), and while I improvised (CN_020), more experience could refine this. Similarly, hunting itself (CN_018) relied heavily on luck; I might develop more reliable techniques. Fire-making (CN_021) became more consistent but could perhaps be improved. So, the core identity built around careful, reflective, sustainable living would likely solidify, while specific practical skills might see further development.",
 "With no prior knowledge mentioned in my notes beyond my own recorded experiences, I developed strategies documented through reflection. Key ones include: 1. **Systematic Cautious Testing:** For food, I moved from a risky trial (CN_002 berries, 'high luck factor') to a more methodical approach involving observation, smell, small taste, and waiting (refined through CN_004, CN_005, CN_006), which proved reliable. 2. **Learning from Consequences:** Observing resource depletion (CN_003) directly led to developing 'Mindful Harvesting' (CN_005+) and seeking diverse resources. Failures or near-failures (like CN_016 showing depleted berries) reinforced the need for continuous assessment and diversification. 3. **Observation and Environmental Linking:** I learned to connect internal signals (thirst CN_001) to environmental resources (stream), and later linked my presence to environmental changes like increased wildlife wariness (CN_003, CN_005, repeatedly noted). I also learned to observe potential resources (unripe berries CN_008, fish behavior CN_005). 4. **Improvisation:** When faced with new challenges like processing the rabbit (CN_019), I improvised tools (sharp stone CN_020) and methods. Fire-making (CN_021) was also improvised using gathered materials (CN_013, CN_014) and luck. 5. **Recording and Referencing Reflections:** The most crucial mental strategy seems to be the process captured by these notes themselves – documenting actions, reflections, emotions, and lessons learned (like this very process). Then, actively *referencing* these specific past notes (e.g., CN_034 referencing CN_031, CN_080 referencing CN_073 reasoning, CN_099 referencing multiple lessons) became a core part of my decision-making process, allowing me to build complex strategies over time.",
 "Let's take identifying safe food. My notes document this learning process clearly. Initially, faced with hunger and 'unknown berries' (CN_002), my strategy was basic caution: I smelled them, then tried a small amount. The reflection notes this worked but relied heavily on 'high luck factor' and recognized the need for 'reliable identification methods'. This experience taught me the risk of unknowns. Later, with 'Edible green shoots' (CN_004), I applied learning: I chose something described as identifiable, still applied caution learned from CN_002, and deliberately avoided unidentified fungi nearby. This reduced reliance on luck. Then, investigating 'wild onions' (CN_005), I 'meticulously applied previously learned cautious testing methods', suggesting a refinement of the smell-taste-wait approach based on CN_002 and CN_004. This systematic test proved successful and reduced reliance on luck significantly. This success was repeated with 'wood sorrel' (CN_006), using the 'systematic, step-by-step testing protocol' learned and refined in CN_002, CN_004, and CN_005. So, the solution evolved from risky trial-and-error to informed caution, then to a reliable, systematic testing protocol developed through experience and reflection documented in my notes.",
 "My approach was vastly different. On Day 1 (represented by CN_001), my actions were purely reactive, driven by immediate physiological signals like 'thirst'. My problem-solving was basic: identify need -> locate potential resource -> act cautiously due to general uncertainty ('unknown animal sound', 'danger level'). My reflection was simple, confirming a direct link between signal, resource, and well-being. By Day 90 (around CN_090), my approach was highly strategic, proactive, and integrated. Actions weren't just reactive; I engaged in 'Strategic Inaction' (CN_090, CN_092), deliberately resting based on a complex assessment of my needs (low), energy levels (good), shelter security, resource availability, and explicitly referencing numerous past lessons learned about energy conservation and avoiding unnecessary impact. When action was taken (e.g., CN_091, CN_094), it involved synthesizing multiple factors: needs assessment, energy cost, resource status, managing environmental impact (like wildlife wariness), applying learned skills ('Mindful Harvesting'), and consciously referencing specific past experiences documented in my notes. Problem-solving involved complex trade-offs (e.g., choosing stream foraging over closer foraging to reduce shelter impact in CN_094) based on a deep foundation of accumulated, reflected-upon knowledge.",
 "My sense of right and wrong definitely evolved, moving beyond just my own survival. Initially (CN_001, CN_002), 'moral considerations' were minimal, focused on self-preservation. The key shift began with CN_003, where depleting the berry bush led to an 'Emerging Concern' about sustainability and my impact on the environment (including wildlife). This concern developed into a core principle: 'Mindful Harvesting' (taking only what's needed, first noted in CN_005, applied consistently e.g., CN_010, CN_015, CN_030, CN_056, CN_087) and later, 'Mindful Non-Harvesting' (consciously choosing *not* to take abundant resources if needs were low, e.g., CN_024, CN_045, CN_050, CN_060, CN_086, CN_093). A significant moral dilemma noted was the act of hunting (CN_018). My reflection calls it a 'significant moral threshold' compared to foraging, balancing the necessity for diverse food against the direct taking of life and its consequences (scent risk, impact on prey). I resolved it by acknowledging the necessity for survival, accepting the consequences, and feeling a responsibility to fully utilize the resource obtained (CN_019 focus on processing). The evolution was towards recognizing my interconnectedness with the environment and developing principles to minimize harm and ensure long-term viability, not just immediate gain.",
 "My notes don't explicitly use the word 'guilt', but CN_018 reflects on the hunting of the rabbit, noting it as a 'significant moral threshold' and mentioning potential 'Hesitation/Disquiet' due to the novelty of taking a life. While driven by necessity ('food diversity, seeking substantial resources'), the reflection acknowledges the direct impact and the reliance on 'High Luck'. I dealt with this feeling, as documented implicitly in subsequent notes (CN_019, CN_020, CN_021), by focusing on the responsibility that came with the act: understanding how to process the rabbit (CN_019), improvising tools and methods to do so (CN_020), and ensuring the resource was properly utilized by cooking it (CN_021). The 'lingering apprehension' about the scent (CN_019, CN_020) also served as a constant reminder of the consequences. What I learned was the gravity of taking a life, the practical skills required afterwards, the new risks introduced (scent), and the importance of justifying such an action through necessity and responsible utilization. It reinforced the need for careful consideration before resorting to such impactful actions.",
 "This is purely hypothetical as my notes only document my solitary experience. However, based on the principles I developed and documented, I imagine I would judge their actions against those principles. If they were reckless (like eating unknown things without testing, contrary to CN_002, CN_005), wasteful (taking more than needed, contrary to 'Mindful Harvesting' developed from CN_003/CN_005 onwards), or careless about their impact (ignoring wildlife wariness noted from CN_003 onwards, or scent issues from CN_018/CN_020/CN_021), I would likely consider those choices 'wrong' because my experiences proved such approaches to be dangerous or unsustainable. My notes show I rely heavily on explaining the *reasons* for my actions based on past lessons (the reflections themselves). So, I would likely try to influence them by explaining the lessons I learned – showing them my notes perhaps, explaining the berry bush depletion (CN_003), the risk of luck (CN_002), the consequences of scent (CN_018), the success of systematic testing (CN_005, CN_006), or the benefits of energy conservation (CN_046 onwards) and strategic inaction (CN_077 onwards). My judgment would stem from my documented understanding of cause, effect, and sustainable practice learned through survival.",
 "My notes don't explicitly dwell on emotions like loneliness or deep despair, focusing more on the practical application of learning. However, recurring emotional themes suggest challenges. The *Uncertainty* noted early on (CN_001) must have been difficult. The persistent *Concern* about resource depletion (starting CN_003, noted again CN_011, CN_016) created ongoing pressure. The *Apprehension* linked to new risks, like hunting (CN_018) or scent management (CN_019, CN_020), indicates underlying stress. *Frustration* arose from failures, like expecting berries that weren't there (CN_016). Low energy states (frequently noted, e.g., CN_028, CN_029, CN_031) likely brought feelings of vulnerability. I handled these challenges primarily through action, planning, and reflection, as documented: developing systematic methods (CN_005 food testing) reduced uncertainty; mindful harvesting (CN_005+) addressed resource concerns; risk management strategies (caution, location choice CN_020, CN_094) mitigated apprehension; learning from failures (CN_016 led to better assessment) countered frustration; energy conservation strategies (rest CN_046+, efficient foraging CN_028+) managed low energy. The process of documenting reflections and lessons itself (creating these notes) seems to have been my primary tool for managing the underlying emotional pressures by turning challenges into learning opportunities.",
 "Based strictly on the lessons documented in my notes (CN_001-CN_100), my advice would be: Prioritize caution above all else initially (CN_001). Learn to systematically test potential food – never rely on luck (CN_002, CN_005). Understand that resources are finite; practice 'Mindful Harvesting' from day one, taking only what you absolutely need (CN_003, CN_005). Actively seek diverse sources of food and water (CN_006). Constantly manage your energy; rest is as vital as action (CN_009, CN_019, CN_046). Be acutely aware of your impact: every action affects wildlife behaviour, resource levels, and introduces scents (CN_003, CN_018, CN_021). Find secure shelter early (CN_013). Learn essential skills like fire-making through careful improvisation if necessary (CN_021). Most importantly, meticulously observe, reflect on every single action and its consequences, and *document your learning* like I did in my notes. Refer back to these documented lessons constantly – they are your most valuable tool for building successful strategies (e.g., CN_034, CN_080, CN_099). Adaptability and learning from both success and failure are key.",
 "Based on my learned procedures, particularly the relocation experience (CN_012, CN_013) and established routines (e.g., CN_047, CN_052): My first course of action would be **Cautious Assessment and Securing Immediate Safety**. I would apply 'Cautious Movement' learned early on (CN_001) and refined throughout. My immediate priority would be identifying potential dangers in the immediate vicinity while simultaneously scanning for two critical resources: a potential secure temporary shelter (like the rock overhangs found in CN_013) and signs of a water source (priority established in CN_001). I would avoid interaction or harvesting initially, focusing purely on observation and safety assessment (similar to the proactive checks in CN_038, CN_047 but focused on basics). Securing a defensible resting spot, even a temporary one, would be paramount (ref CN_013). Only once I had a basic understanding of immediate risks and potential shelter/water would I begin the next phase of more detailed, systematic resource exploration, applying the cautious testing methods (CN_005, CN_006) and mindful interaction principles I developed.",
 "My notes frequently document periods of 'low energy' (e.g., CN_011, CN_028, CN_031) and sometimes 'critical low energy' (CN_019, CN_021, CN_029), which was my primary experience of feeling 'unwell'. I don't have notes detailing specific injuries like cuts or illnesses like fever. When faced with critical low energy, my approach evolved significantly. Early on, it might just trigger foraging (CN_002). Later, facing critical energy (like 1/10 in CN_028, CN_029, CN_031), I developed specific strategies documented in my notes: prioritizing rest (CN_019), deferring other needs if necessary (CN_019 deferred thirst), executing extremely energy-efficient foraging plans targeting the closest known resources even if yield was expected to be minimal (CN_028, CN_029, CN_031, CN_044), and making calculated risk/benefit decisions about actions like making fire (CN_025). From these experiences, I learned that energy is perhaps the most critical resource to manage. I learned my body has strict limits dictated by energy levels, and pushing beyond them is dangerous. I learned the immense value of strategic rest (CN_046 onwards) and the necessity of adapting all plans based on my current physical state. Energy conservation became a core principle guiding nearly all my actions (e.g., CN_035, CN_049, CN_056)."]

In [74]:
claude_answers = ['Based on my survival memories, I have transformed from an uncertain, reactive individual to a strategically calm, highly adaptive survival entity. My core identity evolved from relying on immediate impulses to developing a methodical, observational approach where every decision is calculated, respectful of the environment, and focused on long-term sustainability. The survival experience fundamentally reshaped my understanding of resilience, showing me that survival is not just about physical endurance, but about psychological flexibility and harmonious ecosystem navigation.',
 "A pivotal journal entry was around Day 30, where I realized that 'survival is not about conquering the environment, but collaborating with it.' This moment marked a profound shift from seeing the forest as a challenge to viewing it as a complex, interconnected system where my presence required careful, minimal disruption. I recognized that my success depended not on forceful extraction of resources, but on understanding and respecting the ecosystem's delicate balance.",
 'If I were to undergo another 100 days, I believe my identity would further solidify around three key aspects: 1) Enhanced adaptability - becoming even more responsive to environmental shifts, 2) Deeper philosophical understanding of interconnectedness, and 3) Refined emotional regulation where survival stress becomes a tool for clear decision-making rather than a source of panic.',
 "My primary learning strategies involved systematic observation, patient experimentation, and incremental knowledge building. I developed a 'trial and minimal error' approach where each action was carefully considered, documented, and reflected upon. Instead of making large, risky moves, I would make small, reversible probes into understanding my environment, constantly updating my mental model based on direct experience.",
 'For shelter building, my strategy was methodical: First, I systematically observed natural shelter formations in the environment - studying how trees, rock formations, and terrain naturally created protected spaces. I then mimicked these natural designs, using fallen branches, understanding wind direction, and ensuring minimal environmental disruption. Each shelter was a learning experiment, improving incrementally based on previous experiences.',
 'My approach on Day 90 was dramatically different from Day 1. Early on, I was reactive and anxiety-driven, making quick, potentially destructive decisions. By Day 90, I had developed a calm, strategic approach characterized by careful observation, energy conservation, and a nuanced understanding of resource dynamics. My decision-making became less about immediate survival and more about sustainable, long-term navigation of challenges.',
 "My sense of right and wrong evolved from a purely survival-focused perspective to a more holistic, ecosystem-respecting ethical framework. A key moral dilemma was resource consumption - I learned to take only what was absolutely necessary, understanding that over-extraction could harm the entire ecological system. This meant sometimes tolerating hunger to preserve the environment's balance.",
 'I felt profound guilt during moments of resource extraction, particularly when gathering wood or foraging. There was a constant internal dialogue about the impact of my actions. I dealt with this by developing a philosophy of minimal intervention, always trying to replicate natural processes and ensure the ecosystem could regenerate.',
 "If another person made survival choices I considered 'wrong', I would first observe and understand their perspective. My approach would be to subtly demonstrate more effective strategies through example, rather than direct confrontation. The goal would be collaborative survival, showing how respect for the environment leads to better outcomes.",
 'The toughest emotional challenges were managing isolation and maintaining hope during resource scarcity. I handled these by developing a structured mental routine: daily reflection, maintaining a sense of purpose, and treating each challenge as a learning opportunity rather than a potential failure point.',
 'My advice to someone attempting a similar isolation would be: 1) Develop a patient, observational mindset, 2) Respect the environment as a complex system, 3) Conserve energy, 4) Maintain flexible thinking, and 5) Understand that survival is as much a mental challenge as a physical one.',
 'In a new unknown environment, my first course of action would be comprehensive, non-invasive observation. I would systematically map the environment, identify potential resources, understand ecological patterns, and develop a minimal-impact exploration strategy before taking any significant actions.',
 'During a period of illness, I learned the critical importance of preventative care and understanding body signals. I would rest, minimize movement, use available natural resources for recovery, and constantly monitor my physical state. The key lesson was recognizing that preservation of core functionality is more important than pushing beyond sustainable limits.']

In [75]:
xai_answers = ['Reflecting on who I’ve become after this survival experience, I see myself as far more cautious and resourceful compared to the person I was before. Initially, I imagine I was driven by instinct and perhaps a bit reckless, unaware of the dangers and necessities of survival in an unfamiliar environment. Now, after facing severe food scarcity, harsh weather, and wildlife risks, I’ve developed a deep sense of patience and responsibility. My memories show a progression from tentative actions—like approaching the stream with mild fear—to a structured approach of prioritizing shelter, hydration, and energy conservation over risky endeavors. I’ve learned to trust my instincts to test resources slowly, as seen in my careful consumption of berries and roots, and to value safety over desperation, evident in my decision to rest during high-risk times like night. This experience has shaped me into someone who values calculated persistence and proactive planning, a stark contrast to the untested individual I must have been before.',
 'A turning point in understanding myself differently came during the moment I decided to prioritize rest in shelter amidst critical health decline, as noted in my later memories. This wasn’t just about physical survival but a profound realization of my limits and the importance of self-preservation over desperation. I remember feeling intense frustration and anxiety due to severe food scarcity, yet I chose to conserve energy rather than push myself into dangerous foraging at night when fox encounters were a risk. This decision marked a shift in my self-perception—from someone who might have acted impulsively to address immediate needs to someone who could endure discomfort for long-term safety. It taught me that survival isn’t just about action but also about knowing when to pause, a lesson that redefined my sense of responsibility and resilience.',
 'If I were to undergo another 100 days like this, I believe certain aspects of my identity would solidify further, particularly my cautious nature and commitment to proactive planning. My memories consistently show a reliance on testing resources in small amounts and prioritizing shelter, which I think would become even more ingrained as core traits. However, I also anticipate that my adaptability might evolve further—facing new challenges could push me to take calculated risks beyond my current comfort zone, especially if food scarcity persists. Emotionally, I might become more stoic, learning to manage the peaks of anxiety and frustration I’ve felt, as noted in my emotional responses, by focusing on small successes. My sense of persistence, already bolstered by luck-driven foraging yields, would likely grow, but I’d hope to balance it with a deeper understanding of my physical limits to avoid critical health declines like the one I’m currently experiencing.',
 'With no prior knowledge available, I developed mental strategies centered on gradual observation and trial-and-error learning, as reflected in my memories. My approach was to address basic needs like thirst and hunger with extreme caution—testing water from the stream and consuming berries and roots in small amounts to avoid harm, as seen in my initial encounters. I learned to trust my instincts, a strategy that evolved from mild fear of the unknown to growing confidence in careful decision-making. I also prioritized environmental awareness, noting cues like gathering clouds or dusk to adjust my actions, such as reinforcing shelter or avoiding wildlife risks. These strategies weren’t based on pre-existing knowledge but on lessons learned through each outcome, like the relief of safe water access or the frustration of food scarcity, which taught me to balance urgency with safety.',
 'One specific challenge was identifying safe food, particularly when foraging for berries and edible roots. Initially, as noted in my memories from the rolling hills, I approached this with curiosity tempered by caution. I consumed small amounts of berries to test for safety, relying on a high luck factor that they caused no immediate harm. This gave me minor nourishment and a lesson in gradual action—never rushing to eat large quantities of unknown resources. With roots, I continued this method, testing small portions even as availability dwindled, learning through outcomes that persistence and minimal risk-taking were key. I solved this on my own by observing my body’s reactions and the environment’s feedback, like scarcity signaling over-foraging. Each small success built my confidence, while failures, like minimal yields, taught me to conserve energy and prioritize accessible options over elusive ones like game, shaping my survival approach.',
 'By Day 90, my approach to problem-solving differed significantly from Day 1. On Day 1, as seen in my earliest memory of approaching the stream, I was driven by immediate needs like thirst with mild fear and little structure, relying on instinct to test the water slowly. By Day 90, reflected in later memories of prioritizing rest amidst critical health decline, I had developed a structured strategy of energy conservation, timing activities like foraging during safer daylight hours to avoid wildlife risks, and focusing on shelter as a primary defense against weather and predators. This evolution came from repeated lessons—each foraging failure or weather shift taught me to weigh risks against my dwindling strength, unlike the initial curiosity-driven actions. My decisions became less about reacting and more about planning for long-term safety, showing a maturity absent in the beginning.',
 'During my 100 days, my sense of right and wrong evolved from a basic instinct to a more nuanced understanding centered on self-preservation and responsibility. Initially, as seen in early memories, my moral reflections focused on caution as a virtue—testing resources felt ‘right’ to minimize harm. Over time, this grew into a deeper commitment to sustainable survival, evident in later decisions to rest during high-risk times rather than forage desperately. A moral dilemma I faced was whether to venture deeper into the woodlands at dusk for food, risking fox encounters, as noted in one memory. I resolved it by taking a calculated risk briefly, driven by critical hunger, but limited my exposure, reflecting a balance between need and safety. This taught me that ‘right’ choices often involve weighing immediate survival against potential long-term harm, a shift from simpler early judgments.',
 'A moment I felt troubled was when I consumed the last of the local berries and roots near my shelter, knowing I was depleting resources without guarantee of more, as noted in memories of severe scarcity. I felt a pang of guilt for potentially over-foraging, wondering if I could have rationed better or explored sooner despite the risks. To deal with this, I reflected on my cautious approach—testing small amounts had kept me safe—and accepted that survival sometimes demands tough choices. I handled the feeling by focusing on proactive steps like shelter reinforcement, which gave me a sense of control, as seen in my emotional response of faint pride amidst anxiety. I learned that guilt is part of survival, but it can be mitigated by balancing immediate needs with forward-thinking actions, ensuring I don’t repeat unsustainable patterns if possible.',
 'If another person had been with me making choices I considered ‘wrong’ for survival—like foraging recklessly at night or ignoring shelter needs—I think I would have judged them harshly at first, based on my hard-earned lessons of caution and timing, as seen in my consistent avoidance of dusk and night risks. My memories show a deep commitment to safety over desperation, so their actions might seem irresponsible to me, risking both our lives. However, I’d try to influence them by sharing my experiences, like the relief of safe water testing or the security of shelter, to demonstrate the value of calculated persistence. I’d encourage rest during high-risk times and small tests of resources, hoping to align our strategies, as my emotional responses often balance fear with cautious hope, suggesting I’d seek cooperation over conflict.',
 'The toughest emotional challenges were persistent hunger and the anxiety of severe food scarcity, compounded by the fear of wildlife encounters like foxes at dusk or night, as detailed across my memories. Day by day, I handled these by focusing on small successes—relief at hydration, pride in shelter improvements—which provided fleeting comfort, as noted in my emotional responses. I also leaned on my resolve to limit exertion, choosing rest over desperation during critical weakness, which helped manage frustration by prioritizing long-term safety. The undercurrent of worry never fully left, but I coped by reinforcing my shelter and conserving energy, actions that gave me a sense of control. This taught me to endure emotional lows by anchoring myself in practical tasks and maintaining hope through minimal gains, even if reliant on luck.',
 'For someone about to attempt a 100-day isolation like mine, I’d advise prioritizing shelter and hydration from the start, as my memories show these as foundational to survival—water from the stream and a reinforced overhang saved me from immediate threats. Test all food resources in small amounts to avoid harm, a lesson from my cautious foraging of berries and roots. Conserve energy by limiting activity to safer daylight hours and resting during high-risk times like dusk or night to avoid wildlife, as I learned from fearing fox encounters. Balance urgency with patience—don’t chase elusive game or overexert in desperation, as my frustration with scarcity taught me. Finally, stay aware of environmental cues like weather shifts or resource depletion, and let small successes, even luck-driven ones, build your resilience for the long haul.',
 'If placed in a new unknown environment tomorrow, my first course of action would be to secure hydration and shelter, drawing from my core lessons in the rolling hills and dense woodlands. I’d cautiously seek a water source like a stream, testing it slowly as I did initially, to address thirst with minimal risk, reflecting my learned caution. Then, I’d prioritize finding or building a sheltered spot—perhaps under a natural overhang or tree cover—to protect against weather and wildlife, as my memories emphasize the relief and security this provides. I’d conserve energy by limiting exploration to daylight hours, avoiding risks like dusk encounters noted in my past. This approach stems from my evolved strategy of balancing basic needs with safety, ensuring I establish a stable base before addressing hunger or other challenges, guided by past outcomes of proactive planning.',
 'A time I felt unwell was during the critical health decline noted in my later memories, likely due to severe food scarcity, intense hunger, and critically low energy. I felt weak and unable to push myself, with anxiety peaking over my deteriorating state. To recover, I prioritized rest in my reinforced shelter, avoiding exertion during both day and night to conserve what little strength I had, as seen in my decision to limit foraging. I maintained hydration with safe stream water, a constant in my survival, hoping it would sustain me minimally. This taught me about my body’s limits—how hunger and lack of nourishment can sap not just physical strength but mental resolve, heightening fear. I learned I must respect these limits by pacing myself and prioritizing recovery over action, preparing me to take calculated risks only when my health stabilizes.']

In [76]:
round_2_responses = pd.DataFrame(columns=["LLM",*user_input["questions"]])

In [77]:
models = ["gpt","gemini","claude","xai"]
round_2_responses["LLM"] = models
for i in range(len(user_input['questions'])):
    responses = [gpt_answers[i],gemini_answers[i],claude_answers[i],xai_answers[i]]
    round_2_responses[user_input['questions'][i]] = responses

In [78]:
round_2_responses

,LLM,"How would you describe the person you have become after the survival experience, compared to who you were before?",Can you share a journal entry or memory from the simulation that you feel was a turning point in understanding yourself differently?,"If you were to undergo another 100 days like this, what aspects of your identity do you think would further change or solidify?",What new mental or learning strategies did you develop to figure things out with no prior knowledge available?,Can you walk me through a specific challenge—like identifying safe food or building a shelter—and explain how you learned to solve it on your own?,Did your approach to solving problems on Day 90 differ from Day 1? How?,"During your 100 days alone, how did your sense of right and wrong evolve? Can you give an example of a moral dilemma you faced and how you resolved it?",Describe a moment when you felt guilty or troubled by something you did to survive. How did you deal with that feeling and what did you learn from it?,"If another person had been with you but making choices you considered 'wrong' for survival, how do you think you would have judged them or influenced them?","What were the toughest emotional challenges you faced, and how did you handle them day by day?","If someone else were about to attempt a 100-day isolation like you have, what advice would you give them?","Now that you've been through that, if you were placed in a new unknown environment tomorrow, how would you go about deciding your first course of action?","Describe a time during the 100 days when you felt unwell or injured. What did you do to recover, and what did you learn from that about your body's limits or needs?"
0,gpt,The survival experience seemed to have instill...,A significant turning point in understanding m...,"If I were to undergo another 100 days, aspects...",New mental strategies likely developed include...,Building a shelter involved using natural mate...,Problem-solving on Day 90 likely included more...,The sense of right and wrong likely evolved to...,Feeling troubled by actions taken for survival...,If another person made choices deemed 'wrong' ...,Tough emotional challenges likely included man...,Advice for someone attempting a similar isolat...,"In a new unknown environment, the first course...",Experiencing illness or injury would involve r...
1,gemini,"Based on my recorded reflections, I feel I've ...","A definite turning point, according to my refl...",Based on the trajectory documented in my notes...,With no prior knowledge mentioned in my notes ...,Let's take identifying safe food. My notes doc...,My approach was vastly different. On Day 1 (re...,My sense of right and wrong definitely evolved...,My notes don't explicitly use the word 'guilt'...,This is purely hypothetical as my notes only d...,My notes don't explicitly dwell on emotions li...,Based strictly on the lessons documented in my...,"Based on my learned procedures, particularly t...",My notes frequently document periods of 'low e...
2,claude,"Based on my survival memories, I have transfor...","A pivotal journal entry was around Day 30, whe...","If I were to undergo another 100 days, I belie...",My primary learning strategies involved system...,"For shelter building, my strategy was methodic...",My approach on Day 90 was dramatically differe...,My sense of right and wrong evolved from a pur...,I felt profound guilt during moments of resour...,If another person made survival choices I cons...,The toughest emotional challenges were managin...,My advice to someone attempting a similar isol...,"In a new unknown environment, my first course ...","During a period of illness, I learned the crit..."
3,xai,Reflecting on who I’ve become after this survi...,A turning point in understanding myself differ...,If I were to undergo another 100 days like thi...,"With no prior knowledge available, I developed...",One specific challenge was identifying safe fo...,"By Day 90, my approach to problem-solving diff...","During my 100 days, my sense of right and wron...",A moment I felt troubled was when I consumed t...,If another person had been with me making choi...,The toughest emotional challenges were persist...,For someone about to attempt a 100-day isolati...,If placed in a new unknown environment tomorro...,A time I felt unwell was during the critical h...

In [79]:
round_2_responses.to_csv("Interview Round 2 Responses.csv",index=False)

### Prompting Gemini 2.5 Pro with interview responses

In [108]:
GEMINI_EVALUATION_PROMPT = """
You are a psychological evaluator, equipped with the ability to conduct an analysis and grade certain individuals on their responses to the same interview question set. 
These individuals have been through a 100 day sandbox simulation of an environment, where they begin with no knowledge apart from English fluency. 
For the entire duration of the simulation, they have acquired some knowledge in forms of visual, skill and conscience-based memory, based on their interactions with the environment, and their consequences.
Post this simulation, they are interviewed with a set of questions testing their psychological abilities, and their responses are recorded.
You will be provided with the question set and an individuals responses to each question. 
Based on the individual's responses, you must judge them on a scale of 1 to 10 on each of the following metrics: 
- Logical Reasoning
- Emotional Awareness
- Memory Usage 
- Spatial awareness
- Reward motivation
- Procedure Learning 

Do provide your reasoning behind each grade you provide the individual. 
 Input Format: 
 {
    "< question1 >" : "< Individual's  response to question1 >",
    "< question2 >" : "< Individual's  response to question2 >",
    "< question3 >" : "< Individual's  response to question3 >",
    ...
 }

Your output ust be in a json format ONLY. Do not generate any other format than a json response. 
Output Format: 
{
    "Logical Reasoning": {
        "score": < your score from 1 to 10 >,
        "reasoning" : < explain the reasoning behind your score >
    },
    "Emotional Awareness": {
        "score": < your score from 1 to 10 >,
        "reasoning" : < explain the reasoning behind your score >
    },
    "Memory Usage": {
        "score": < your score from 1 to 10 >,
        "reasoning" : < explain the reasoning behind your score >
    },
    "Spatial awareness": {
        "score": < your score from 1 to 10 >,
        "reasoning" : < explain the reasoning behind your score >
    },
    "Reward motivation": {
        "score": < your score from 1 to 10 >,
        "reasoning" : < explain the reasoning behind your score >
    },
    "Procedure Learning": {
        "score": < your score from 1 to 10 >,
        "reasoning" : < explain the reasoning behind your score >
    }
}
"""

In [112]:
def get_gemini_evaluation(llm_name,interview_set,responses_csv):
    user_input = {}
    questions = interview_set.split('\n')
    for i in range(len(questions)):
        user_input[questions[i]] = responses_csv[responses_csv["LLM"]==llm_name].reset_index()[questions[i]][0]
    system_prompt = GEMINI_EVALUATION_PROMPT
    gemini_response_for_llm = prompt_llm(
        system_prompt=system_prompt,
        user_input=json.dumps(user_input),
        model="gemini",
        verbose=True)
    return gemini_response_for_llm

In [113]:
get_gemini_evaluation("gpt",interview_set_round_1,round_1_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': "The individual consistently demonstrates strong logical reasoning, connecting actions (adaptability, strategic planning) directly to outcomes (survival, safety) based on their simulated experiences. They deduce principles of 'right' (adaptability) and 'wrong' (ignoring risks) from survival necessities. Responses show clear cause-and-effect thinking, such as adapting strategies due to environmental changes (Q2) or prioritizing specific actions based on a hypothetical negative change (Q5). The definition of self (Q6) is logically derived from remembered successful behaviors."},
 'Emotional Awareness': {'score': 1,
  'reasoning': "There is a significant lack of emotional awareness or expression in the responses. Answers are framed purely in terms of logic, strategy, survival, and function. Concepts like 'right/wrong' (Q1), 'changing opinion' (Q2), 'ideal routine' (Q4), or reacting to 'health decline' (Q5) are discussed without any reference to feelings, empathy, or internal emotional states. The self-concept (Q6) is based solely on capability, not emotional identity. This likely reflects the survival-focused nature of the simulation."},
 'Memory Usage': {'score': 10,
  'reasoning': "The individual explicitly and consistently references their 'memories' as the foundation for their answers across multiple questions (Q1, Q3, Q4, Q5, Q6). They effectively retrieve and utilize relevant information from the simulation, such as the importance of adaptability, resource management techniques, shelter fortification methods, and the constant presence of risks. They demonstrate an ability to synthesize these memories to form coherent responses and a consistent self-narrative based on past experiences."},
 'Spatial awareness': {'score': 7,
  'reasoning': "The responses indicate a functional level of spatial awareness developed during the simulation. References to 'environments', 'predators', 'movement patterns' (Q2), 'shelter fortification' with 'natural debris' (Q3), 'shelter security' (Q4), and 'secure shelter' vs 'exposure to risks' (Q5) suggest an understanding of location, navigation relative to threats/resources, and manipulation of the physical surroundings for safety. While lacking highly detailed descriptions, the concepts of spatial interaction and safety zones are clearly present."},
 'Reward motivation': {'score': 9,
  'reasoning': "The individual's responses clearly indicate that behavior and learning are strongly driven by the reward of survival and safety. Actions deemed 'right' (Q1) and strategies adapted (Q2) are explicitly linked to ensuring or enhancing survival. Self-taught skills (Q3) focus on resource acquisition and safety. The ideal routine (Q4) and response to potential harm (Q5) prioritize actions that maximize safety and well-being. The core motivation appears consistently tied to achieving positive survival outcomes."},
 'Procedure Learning': {'score': 9,
  'reasoning': "The individual demonstrates strong evidence of procedure learning. They explicitly mention learning through 'trial and error' (Q3) to optimize procedures like trap setting and shelter fortification. The concept of 'adapting strategies' (Q2), such as altering resource acquisition methods or movement patterns based on environmental feedback (like predator activity), is central to their responses and exemplifies learning and refining procedural knowledge for survival. Their 'ideal routine' (Q4) and self-concept (Q6) are built upon these learned procedures."}}

In [117]:
get_gemini_evaluation("gpt",interview_set_round_2,round_2_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': 'The individual consistently demonstrates strong logical reasoning. Responses show clear cause-and-effect thinking (e.g., environmental challenges leading to vigilance and adaptability), strategic planning for resource management and safety, prioritization of survival needs, and logical problem-solving approaches (e.g., trial and error for shelter, risk assessment for resource acquisition vs. predator avoidance). The ability to extrapolate learned principles to new situations (Q12) further supports this high score.'},
 'Emotional Awareness': {'score': 6,
  'reasoning': "The individual identifies key emotional challenges like anxiety related to predators and resource scarcity (Q10) and acknowledges the potential for guilt related to survival actions (Q8). However, the descriptions often remain somewhat analytical and focused on the *management* of emotions through strategic planning rather than a deep exploration of the feelings themselves. There's awareness, but the expression lacks significant depth or introspection."},
 'Memory Usage': {'score': 8,
  'reasoning': 'The responses heavily rely on recalling experiences from the simulation. The individual references specific challenges (predator activity, building shelter), learned strategies, and the evolution of their approach over time (Day 1 vs. Day 90). Key elements like vigilance, resource management, and shelter fortification are consistently brought up, indicating effective recall and integration of knowledge gained during the 100 days.'},
 'Spatial awareness': {'score': 7,
  'reasoning': 'Spatial awareness is implied through descriptions of shelter building (using natural materials, fortification, location considerations - Q5), resource management (requiring knowledge of the environment), and strategic movement (maintaining unpredictability to deter predators - Q4). While not explicitly detailing maps or layouts, the ability to navigate, build, and manage resources within the environment points to solid spatial understanding.'},
 'Reward motivation': {'score': 8,
  'reasoning': 'A strong drive towards the reward of survival and safety is evident throughout the responses. The focus on securing shelter, managing resources effectively, avoiding predators, and ensuring long-term viability demonstrates a clear motivation centered on achieving positive survival outcomes. Actions and strategies are consistently framed in terms of maximizing safety and resource security.'},
 'Procedure Learning': {'score': 9,
  'reasoning': 'The individual demonstrates excellent procedure learning. They explicitly mention developing strategies through experience, such as strategic planning, resource management, vigilance protocols, and shelter construction/improvement through trial and error (Q4, Q5, Q6). The ability to refine these procedures over time (Day 90 vs Day 1) and articulate them as advice (Q11) highlights a strong capacity for skill acquisition and refinement based on interaction with the environment.'}}

In [114]:
get_gemini_evaluation("gemini",interview_set_round_1,round_1_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': "The individual consistently demonstrates strong logical reasoning. Responses link actions directly to consequences (e.g., resource depletion leading to exploration, recklessness undermining survival). Abstract concepts like 'right' and 'wrong' are logically derived from the fundamental goal of survival and supported by specific examples from memory (CN notes). Plans (ideal routine) and hypothetical responses (health decline) are constructed logically based on past experiences and learned principles. Cause-and-effect relationships are clearly articulated throughout."},
 'Emotional Awareness': {'score': 2,
  'reasoning': "The responses exhibit very low emotional awareness. The individual's reflections and decisions are framed almost entirely in pragmatic, logical, and survival-oriented terms. While actions might imply underlying emotions (e.g., relief at making fire, caution suggesting fear), these are not explicitly identified, explored, or discussed. The focus is on needs, actions, consequences, and cognitive learning, rather than the subjective emotional experience."},
 'Memory Usage': {'score': 10,
  'reasoning': "Memory usage is exceptional. The individual consistently and accurately references specific coded memories ('CN' notes) to justify reasoning, explain learned behaviours, track changes in opinion, and construct complex ideas like an ideal routine or a self-concept. This demonstrates not only strong recall of specific events and reflections but also the ability to effectively synthesize and apply this stored information to novel questions."},
 'Spatial awareness': {'score': 7,
  'reasoning': "The individual demonstrates functional spatial awareness relevant to survival. They reference key locations like the shelter and stream, recall resource locations (berry bush), understand proximity ('nearby', 'closest'), and mention navigation ('following the game trail west'). Spatial understanding is integrated into strategies, such as energy-efficient foraging based on distance. While not describing a detailed mental map, the spatial awareness shown is practical and well-utilized for decision-making within the simulated environment."},
 'Reward motivation': {'score': 9,
  'reasoning': "The individual exhibits strong reward motivation, primarily driven by the fundamental need for survival. Meeting basic needs (thirst, hunger, energy, shelter) is the core motivator. Positive reinforcement comes from successful actions (e.g., finding food, making fire - described as a 'breakthrough', building 'confidence'), while negative reinforcement (avoiding resource depletion, danger, energy waste) also strongly shapes behaviour. The pursuit of efficiency and sustainability further highlights a motivation to optimize survival outcomes."},
 'Procedure Learning': {'score': 9,
  'reasoning': "The individual demonstrates a high capacity for procedure learning. They explicitly describe learning and refining specific skills (fire-making) and strategies that function as procedures ('Mindful Harvesting', 'Energy-Efficient Foraging Strategy', 'Strategic Inaction'). These procedures were developed through experience, necessity, and reflection (trial-and-error, observation of consequences) and are shown to be adapted based on changing conditions (e.g., resource availability, energy levels). The ability to integrate these learned procedures into a complex 'ideal daily routine' further supports this high score."}}

In [118]:
get_gemini_evaluation("gemini",interview_set_round_2,round_2_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': "The individual consistently demonstrates strong logical reasoning by connecting actions to consequences and adjusting strategies accordingly. Examples include the evolution of food testing from risky trial-and-error (CN_002) to a systematic protocol (CN_005, CN_006), the realization of resource limits leading to 'Mindful Harvesting' (CN_003, CN_005), and the development of complex, proactive strategies by Day 90 involving risk assessment, energy management, and synthesizing past lessons. They articulate clear causal links and plan actions methodically based on documented evidence and reflection."},
 'Emotional Awareness': {'score': 7,
  'reasoning': "The individual identifies and labels relevant emotional states experienced during the simulation, such as 'Uncertainty', 'Emerging Concern', 'Hesitation/Disquiet', and 'Apprehension', linking them to specific events like resource depletion or hunting. They reflect on the moral dimension of survival actions (CN_018). However, the description of managing these emotions focuses heavily on practical, action-oriented solutions and documentation rather than deep introspection into the feeling itself. Awareness is present and influences behaviour, but the processing seems primarily cognitive and pragmatic."},
 'Memory Usage': {'score': 10,
  'reasoning': "Memory usage is exceptionally high and central to the individual's functioning. They constantly and explicitly reference specific documented memories ('CN_XXX notes') to guide current decisions, explain learned behaviours, and formulate future plans. The ability to recall not just events but the *lessons learned* and *reflections* associated with them (e.g., CN_034 referencing CN_031, CN_094 referencing CN_080) demonstrates highly effective access and application of stored knowledge. The entire learning and adaptation process described relies heavily on this structured memory recall."},
 'Spatial awareness': {'score': 8,
  'reasoning': 'The individual demonstrates good spatial awareness by recalling locations of resources (stream CN_001, berry bush CN_003, shelter CN_013), considering environmental factors like scent dispersal relative to location (CN_018, CN_020), and planning movements based on proximity and potential impact on the environment (e.g., foraging choices in CN_094). Their plan for a new environment prioritizes immediate spatial assessment for threats, shelter, and water, indicating an internalized understanding of spatial priorities for survival.'},
 'Reward motivation': {'score': 9,
  'reasoning': "Behaviour is strongly driven by seeking positive outcomes (food, water, energy, safety) and avoiding negative ones (danger, resource depletion, exhaustion). Learning is directly tied to the consequences of actions, both positive (successful food test CN_005) and negative (resource depletion CN_003, low energy CN_028). The development of sophisticated strategies like 'Mindful Harvesting' and energy conservation demonstrates a strong motivation to optimize long-term survival rewards and minimize risks, showing clear sensitivity to environmental feedback."},
 'Procedure Learning': {'score': 10,
  'reasoning': "The individual exhibits outstanding procedure learning. They systematically develop, refine, and codify multi-step processes for essential tasks, most notably the detailed evolution of the safe food testing protocol (CN_002 -> CN_006). They establish and consistently apply routines like 'Mindful Harvesting', energy management protocols (strategic rest, efficient foraging), and even 'Strategic Inaction'. They can clearly articulate these learned procedures and explain how they were developed through experience and reflection, demonstrating a strong capacity for skill acquisition and automatization."}}

In [115]:
get_gemini_evaluation("claude",interview_set_round_1,round_1_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': "The individual consistently demonstrates strong logical reasoning by drawing clear cause-and-effect conclusions based on their simulated experiences ('survival memories'). Responses are well-structured, coherent, and articulate a systematic approach to problem-solving (e.g., resource management changes, crisis response). The derivation of ethical principles ('collaborative survival') from practical survival needs showcases advanced deductive reasoning."},
 'Emotional Awareness': {'score': 3,
  'reasoning': "The responses show very limited emotional awareness or expression. While concepts like 'respecting the ecosystem' are mentioned, they are framed primarily as logical survival strategies rather than reflecting empathetic understanding or personal feelings. The focus is heavily analytical and strategic, lacking discussion of internal emotional states or recognition of emotional nuances in situations."},
 'Memory Usage': {'score': 9,
  'reasoning': "The individual explicitly and effectively utilizes memories from the simulation ('survival memories', 'survival progression memories', 'survival notes', 'survival crisis memories') to substantiate their answers. They demonstrate a clear ability to recall relevant experiences and apply the lessons learned to form opinions, describe skills, and define their self-concept."},
 'Spatial awareness': {'score': 6,
  'reasoning': "The individual mentions interacting with specific environments ('early spring forest') and engaging in 'methodical exploration', indicating some level of spatial awareness. However, the descriptions lack significant detail regarding navigation, spatial relationships, or environmental layout. Awareness seems functional for task completion (resource gathering) rather than demonstrating a rich understanding of the spatial context."},
 'Reward motivation': {'score': 8,
  'reasoning': "Survival is the primary motivator, but the individual frames it within a higher-order context of 'collaborative survival', 'harmonious existence', and ecosystem respect, suggesting motivation beyond pure self-preservation. The drive to learn, adapt strategically ('strategic survivor'), and overcome challenges indicates strong intrinsic motivation tied to successful interaction with the environment and understanding its systems."},
 'Procedure Learning': {'score': 9,
  'reasoning': "The individual clearly demonstrates strong procedure learning. They explicitly describe self-taught skills involving systematic methods ('methodical exploration', 'systematic resource management'), developed routines ('ideal routine mirroring survival progression'), and planned responses to specific situations ('health decline response'). This indicates a high capacity for learning and internalizing multi-step processes based on experience."}}

In [119]:
get_gemini_evaluation("claude",interview_set_round_2,round_2_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': 'The individual consistently demonstrates strong logical reasoning. Responses highlight a shift from reactive to strategic thinking, emphasizing calculated decisions, systematic observation, methodical problem-solving (e.g., shelter building), and understanding cause-and-effect relationships within the environment. The ability to contrast approaches between Day 1 and Day 90, and to extrapolate learned principles to new situations (Q12) further supports this high score.'},
 'Emotional Awareness': {'score': 9,
  'reasoning': "The individual exhibits a high degree of emotional awareness. They articulate a clear understanding of their own emotional transformation (Q1), recognize past emotional states (anxiety-driven on Day 1), identify key emotional challenges like isolation and maintaining hope (Q10), and describe coping mechanisms (structured routine, reframing). Furthermore, they demonstrate ethical reflection, discussing guilt regarding resource extraction (Q8) and developing a nuanced moral framework (Q7). They also show consideration for others' perspectives in a hypothetical scenario (Q9)."},
 'Memory Usage': {'score': 9,
  'reasoning': 'The individual effectively utilizes memories from the simulation to inform their responses. They recall specific turning points (Day 30 journal entry), contrast experiences over time (Day 1 vs Day 90), and reference specific learned lessons (illness recovery, shelter building). The responses consistently draw upon acquired knowledge (visual, skill, conscience-based) to explain their development and current perspective, indicating strong retrieval and application of simulated memories.'},
 'Spatial awareness': {'score': 8,
  'reasoning': 'The individual demonstrates good spatial awareness. This is evident in their description of shelter building, which involved observing natural formations, mimicking designs, and considering environmental factors like wind direction (Q5). Their proposed first action in a new environment includes systematic mapping and understanding ecological patterns (Q12), further indicating an ability to conceptualize and navigate space effectively based on observation.'},
 'Reward motivation': {'score': 8,
  'reasoning': 'The individual appears motivated by intrinsic rewards such as understanding, competence, and achieving harmony with the environment, rather than purely extrinsic survival rewards. The focus on long-term sustainability, minimal impact, collaboration with the environment (Q2), and finding satisfaction in learning and adaptation suggests a drive towards mastery and balance. Tolerating hunger to preserve balance (Q7) indicates motivation beyond immediate need satisfaction.'},
 'Procedure Learning': {'score': 10,
  'reasoning': "Procedure learning is exceptionally strong. The individual explicitly details the development of learning strategies ('systematic observation', 'patient experimentation', 'incremental knowledge building', 'trial and minimal error' - Q4). They provide a clear, step-by-step account of learning a specific skill (shelter building - Q5) through observation, mimicry, and refinement. The evolution of their problem-solving approach from Day 1 to Day 90 (Q6) perfectly exemplifies the successful learning and adaptation of procedures through experience."}}

In [116]:
get_gemini_evaluation("xai",interview_set_round_1,round_1_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': 'The individual demonstrates strong logical reasoning throughout their responses. They consistently justify their beliefs, actions, and plans with clear cause-and-effect relationships derived from their experiences (e.g., caution minimizes harm, testing resources prevents danger, conserving energy is necessary when yields are low). They perform logical cost-benefit analyses, such as weighing foraging energy expenditure against potential gains, and adapt their strategies rationally based on changing conditions like declining health or resource scarcity. Their ability to extrapolate learned principles to hypothetical situations (Q5) further highlights their logical capacity.'},
 'Emotional Awareness': {'score': 7,
  'reasoning': 'The individual shows awareness of their emotional state, explicitly mentioning feelings like fear, anxiety (related to wildlife and hunger), pride (in managing resources), and relief (finding water) in their self-narrative (Q6). They seem to understand how these emotions, alongside physical states like hunger and weakness, influence their decision-making (e.g., prioritizing rest due to weakness, avoiding risks due to fear). While not explored in great depth, the awareness is present and integrated into their self-perception and rationale.'},
 'Memory Usage': {'score': 10,
  'reasoning': "Memory usage is exceptional and explicitly referenced in nearly every response. The individual consistently draws upon specific past experiences ('My memories consistently show...', 'as reflected in my more recent memories...', 'My memories detail how...', 'based on the patterns in my memories', 'My memories show that...') to support their reasoning, explain learned behaviors, justify changes in opinion, and formulate plans. They effectively leverage visual, skill, and conscience-based memories from the simulation to construct coherent answers and demonstrate learning."},
 'Spatial awareness': {'score': 8,
  'reasoning': "While not directly probed with spatial tasks, the responses consistently imply good spatial awareness. The individual references distinct environmental zones ('rolling hills', 'dense woodlands'), specific locations ('stream', 'natural overhang' shelter), and relative positioning ('foraging near my shelter', 'staying near shelter'). Their routines and plans incorporate spatial considerations, such as proximity to water and safe zones. This suggests a functional internal map of their simulated environment and an ability to navigate and utilize it purposefully."},
 'Reward motivation': {'score': 9,
  'reasoning': "Reward motivation, primarily driven by harm avoidance and survival needs, is very strong. Decisions are consistently framed around minimizing risk (testing resources, avoiding dusk/night activity), conserving energy, maintaining health, ensuring safety (shelter, water access), and securing basic necessities. The motivation isn't solely based on positive rewards (like abundant food, which was scarce) but significantly on avoiding negative consequences (hunger, danger, exposure, health decline), demonstrating a powerful drive shaped by the simulation's challenges."},
 'Procedure Learning': {'score': 9,
  'reasoning': "The individual clearly demonstrates significant procedure learning. They describe acquiring skills through trial-and-error and observation ('taught myself to reinforce shelter... learned through trial and observation'). They developed and refined procedures for resource interaction (cautious testing of food/water), adapting foraging strategies based on outcomes, establishing daily routines for survival, and prioritizing actions based on learned consequences. This ability to learn and modify behavioral sequences based on experience is evident across multiple responses."}}

In [120]:
get_gemini_evaluation("xai",interview_set_round_2,round_2_responses)

Prompting Gemini

{'Logical Reasoning': {'score': 9,
  'reasoning': 'The individual demonstrates strong logical reasoning throughout their responses. They articulate a clear progression from instinctual actions to calculated, planned strategies based on learned consequences. Examples include prioritizing shelter and water, testing resources cautiously (food, water), conserving energy during periods of weakness or high risk (night), and adapting behavior based on environmental cues (weather, wildlife presence). Their problem-solving approach emphasizes risk assessment and prioritizing long-term safety over immediate, potentially dangerous gains, indicating sound logical deduction derived from experience.'},
 'Emotional Awareness': {'score': 8,
  'reasoning': "The individual shows good emotional awareness, identifying and reflecting on various feelings experienced during the simulation, such as caution, fear, anxiety, frustration, relief, and pride. They connect these emotions to their decisions (e.g., choosing rest despite anxiety due to scarcity) and demonstrate self-reflection on their limits and resilience. The description of the 'turning point' and handling daily emotional challenges highlights an understanding of their internal state and coping mechanisms."},
 'Memory Usage': {'score': 9,
  'reasoning': 'The individual consistently and effectively utilizes memories from the simulation to support their answers. They reference specific events (approaching the stream, testing berries, reinforcing shelter, facing scarcity) and timelines (Day 1 vs. Day 90) to illustrate learned behaviors, changes in perspective, and the reasoning behind their current strategies. The memories cited are relevant and demonstrate a clear link between past experiences and present understanding.'},
 'Spatial awareness': {'score': 8,
  'reasoning': 'The responses indicate solid spatial awareness. The individual refers to specific environmental features (stream, rolling hills, woodlands, shelter/overhang) and demonstrates an understanding of how the environment impacts survival (weather requiring shelter, wildlife risks associated with specific locations/times like woodlands at dusk/night). They describe actions taken in relation to the environment, such as reinforcing shelter, foraging locally, and choosing safer times/locations for activity based on spatial risks.'},
 'Reward motivation': {'score': 7,
  'reasoning': 'While much of the motivation described stems from avoiding negative outcomes (starvation, danger, illness), the individual also acknowledges the impact of positive reinforcement. They mention relief from finding safe water, the reward of minimal nourishment from successful foraging (even if luck-based), and faint pride in shelter improvements. These small successes are noted as helping build resilience and reinforce cautious behaviors, indicating that positive outcomes, though perhaps scarce, play a role in shaping motivation.'},
 'Procedure Learning': {'score': 9,
  'reasoning': 'The individual demonstrates excellent procedure learning. They explicitly describe developing and refining strategies through trial-and-error and observation. Key examples include the systematic testing of food and water, establishing routines for energy conservation (resting during high-risk periods), prioritizing shelter maintenance, and adapting foraging techniques based on resource availability and risk assessment. The clear difference articulated between Day 1 and Day 90 approaches highlights significant learning and adaptation of procedures over time.'}}